Add helpers for checking whether a transactions must be added to the limbo and needs to be acked
tarantool/tarantool pull request #10249
Opened 2024-07-15 11:15 UTC by CuriousGeorgiy

This patch series adds helpers for checking whether a transactions must be added to the limbo and whether a transaction needs to be acked.

2024-07-16 12:10 UTC, Serpentian requested changes
Thank you for the patch, but I'd rather merge it alongside with the main one. Now it's easy to miss some places and IMHO, it'll look confusing in master and will complicate the existing code.

2024-07-17 06:46 UTC, CuriousGeorgiy commented on src/box/txn.h
> +	return (txn->flags & TXN_WAIT_ACK) != 0;
I wrote it this way to extend it for `TXN_EARLY_ACK` like this: `return (txn->flags & (TXN_WAIT_ACK | TXN_EARLY_ACK)) != 0;`.

2024-07-17 06:58 UTC, CuriousGeorgiy commented on src/box/txn.c
>  	if (req == NULL)
Yeah, sorry, my bad, replaced it everywhere.

2024-07-17 07:00 UTC, CuriousGeorgiy commented on src/box/txn.c
>  		 * another WAL write. Can't be done until it works
This place below boggled me:
https://github.com/tarantool/tarantool/blob/4cac1677c88a0ee13944d8dc44b10813738bb445/src/box/txn.c#L940-L950

I think we can simply add a check like this below:
```c++
if (!txn_needs_ack(txn))
	txn_set_flags(txn, TXN_WAIT_ACK);
txn_set_flags(txn, TXN_WAIT_SYNC);
```

2024-07-17 13:26 UTC, CuriousGeorgiy commented on src/box/txn.c
>  		goto rollback;
Fixed.

2024-07-17 16:02 UTC, Serpentian commented on src/box/txn.c
>  		 * another WAL write. Can't be done until it works
I'd rather left it as it is. Why do we need this additional condition here?

2024-07-17 16:03 UTC, Serpentian commented on src/box/txn.c
>  		goto rollback;
It's still not there, AFAICS)

2024-07-17 16:22 UTC, CuriousGeorgiy commented on src/box/txn.c
>  		 * another WAL write. Can't be done until it works
According to the RFC [^1], we should not always add the `TXN_WAIT_ACK` flag in this place:

> Given the new flag the possible flag combinations for limbo entries are are:
> 
> - `TXN_EARLY_ACK` only: for async transactions in the limbo which don’t have any sync > transactions before them (thus these async transactions are already ACK-ed to the user)
> - `TXN_WAIT_ACK + TXN_WAIT_SYNC` : for synchronous transactions
> - `TXN_WAIT_SYNC + TXN_EARLY_ACK`: for async transactions in the limbo after some sync transaction (thus these transactions were not yet ACKed to the user). As soon as the preceding sync transaction gets confirmed, these transactions are ACKed to the user, and their flag is changed to `TXN_EARLY_ACK` (`TXN_WAIT_SYNC` is removed). At the same time they become the first ones in the queue.

If an asynchronous transaction came, we should only add the `TXN_WAIT_SYNC` flag to it. Not sure about the best way to handle this logic here.

[^1]: https://www.notion.so/tarantool/Async-in-the-presence-of-sync-9456c50afefc4b2dbe5514d8e1582803?pvs=4#f3adc2554f414e599186a268e0f9e429

2024-07-17 16:23 UTC, CuriousGeorgiy commented on src/box/txn.c
>  		goto rollback;
Sorry, the rewording got dropped for some reason, should be fine now.

2024-07-22 15:02 UTC, Serpentian commented on src/box/txn.c
>  		 * another WAL write. Can't be done until it works
Can we leave this place untouched for now? It looks strange without the main patch and interferes with code readability:

```c
if (!txn_has_flag(txn,  TXN_WAIT_ACK)
    txn_set_flags(txn, TXN_WAIT_ACK)
txn_set_flags(txn, TXN_WAIT_SYNC)
```

2024-07-23 15:44 UTC, sergepetrenko reviewed
I'd rather not move on with this refactoring until we see the full picture with the main patch.

For example, instead of introducing helpers like `txn_must_be_in_limbo`, which replaces `TXN_EARLY_ACK | TXN_WAIT_SYNC`, you could rearrange the txn flags and introduce a separate `TXN_MUST_BE_IN_LIMBO` flag.

Same for `txn_needs_ack`.

So the flags would be:
`TXN_MUST_BE_IN_LIMO` (feel free to find a better name).
`TXN_NEEDS_ACK`
`TXN_EARLY_ACK`.

Then `TXN_MUST_BE_IN_LIMBO` is set for all 3 types of transactions: async-before-sync, sync, and async-after-sync transactions.
`TXN_NEEDS_ACK`  is set for async-before-sync and sync ones.
`TXN_EARLY_ACK` is set for async-before-sync ones.

Alternatively you could remove `TXN_EARLY_ACK` altogether and instead introduce `TXN_IS_SYNC` which is set only for the sync transactions.

Anyway, if predicates `txn_must_be_in_limbo`/`txn_needs_ack` become identical to checking a single flag like `txn_has_flag(txn, TXN_MUST_BE_IN_LIMBO)`, I think checking the flag directly would be more straightforward.

2024-08-25 11:33 UTC, CuriousGeorgiy commented on src/box/txn.c
>  		 * another WAL write. Can't be done until it works
Thanks for the feedback! Closing this PR in the light of #10461.

2024-08-25 11:34 UTC, CuriousGeorgiy commented
Thanks for the feedback! Closing this PR in the light of #10461.

2024-08-25 11:34 UTC, closed without merging