box: allow to access to the granted role in _vuser space
tarantool/tarantool pull request #10747
Opened 2024-10-27 21:45 UTC by mkostoevr

Prior to this patch it was not possible for a user to see any role in the `_vuser` space except the one created by him and the `public` one.

Let's also make it possible to see roles that he is granted with, so calls to the `box.schema.user.info()` functions won't fail if a user has a non-'public' role granted.

NO_DOC=bugfix

2024-10-28 18:13 UTC, drewdzzz requested changes
Thanks for the patch!
I left a couple of suggestions.

2024-10-28 18:13 UTC, drewdzzz commented on src/box/sysview.c
> +	const char *type_str =
You could check the type right in the user object:
```c
struct user *role = user_by_id(uid);
if (role->def->type == SC_ROLE) {
    ....
}
```
Or do I miss something?

2024-10-28 18:13 UTC, drewdzzz commented on test/box-luatest/gh_10057_user_role_test.lua
> +        box.schema.user.grant('testuser', 'manager')
Let's check a transition in another test: role is granted to another role that is granted to a user.

2024-10-30 15:44 UTC, xuniq approved these changes

2024-10-30 15:44 UTC, xuniq commented on changelogs/unreleased/gh-10057-box-schema-user-info.md
> +  user is granted with a non-'public' role (gh-10057).
```suggestion
* Fixed a bug when the `box.schema.user.info()` function could fail if a current
  user was granted with a non-`public` role (gh-10057).
```

2025-06-10 22:04 UTC, mkostoevr commented on src/box/sysview.c
> +	const char *type_str =
<details>

<summary>Right.</summary>

```diff
--- a/src/box/sysview.c
+++ b/src/box/sysview.c
@@ -326,17 +326,9 @@ vuser_filter(struct space *source, struct tuple *tuple)
                return true;
 
        /* Allow access to a role granted to the effective user. */
-       uint32_t type_str_len;
-       const char *type_str =
-               tuple_field_str(tuple, BOX_USER_FIELD_TYPE, &type_str_len);
-       if (type_str == NULL)
-               return false;
-       if (type_str_len == strlen("role") &&
-           !strncmp(type_str, "role", type_str_len)) {
-               struct user *role = user_by_id(uid);
-               if (role_is_granted(role, cr->auth_token))
-                       return true;
-       }
+       struct user *role = user_by_id(uid);
+       if (role->def->type == SC_ROLE && role_is_granted(role, cr->auth_token))
+               return true;
 
        return false;
 }
```

</details>

2025-06-10 22:18 UTC, mkostoevr commented on test/box-luatest/gh_10057_user_role_test.lua
> +        box.schema.user.grant('testuser', 'manager')
<details>

<summary>Made the check transitive.</summary>

```diff
diff --git a/src/box/user.cc b/src/box/user.cc
index 0501283e72..3be61fa178 100644
--- a/src/box/user.cc
+++ b/src/box/user.cc
@@ -912,7 +912,20 @@ role_revoke(struct user *grantee, struct user *role)
 bool
 role_is_granted(struct user *role, uint8_t auth_token)
 {
-       return user_map_is_set(&role->users, auth_token);
+       /* Check if the role is granted directly. */
+       if (user_map_is_set(&role->users, auth_token))
+               return true;
+
+       /* Check if the role is granted transitively. */
+       struct user_map_iterator it;
+       user_map_iterator_init(&it, &role->users);
+       struct user *transitive_role;
+       while ((transitive_role = user_map_iterator_next(&it))) {
+               if (transitive_role->def->type == SC_ROLE &&
+                   role_is_granted(transitive_role, auth_token))
+                       return true;
+       }
+       return false;
 }
 
 int
diff --git a/test/box-luatest/gh_10057_user_role_test.lua b/test/box-luatest/gh_10057_user_role_test.lua
index 316e96a83b..cbf103ab62 100644
--- a/test/box-luatest/gh_10057_user_role_test.lua
+++ b/test/box-luatest/gh_10057_user_role_test.lua
@@ -35,3 +44,24 @@ g.test_user_role = function(cg)
         box.session.su(original_user)
     end)
 end
+
+g.test_transitive_role = function(cg)
+    cg.server:exec(function()
+        box.schema.user.create('testuser')
+        box.schema.role.create('staff')
+        box.schema.role.create('manager')
+        box.schema.role.grant('manager', 'staff')
+        box.schema.user.grant('testuser', 'manager')
+
+        local original_user = box.session.effective_user()
+        box.session.su('testuser')
+
+        -- Check the user has an access to the 'manager' role.
+        t.assert_equals(#box.space._vuser.index.name:select('manager'), 1)
+
+        -- Check the user has a transitive access to the 'staff' role.
+        t.assert_equals(#box.space._vuser.index.name:select('staff'), 1)
+
+        box.session.su(original_user)
+    end)
+end
```

</details>

2025-06-11 21:24 UTC, drewdzzz reviewed
Thank you for the fixes!
I have a couple of comments.

2025-06-11 21:24 UTC, drewdzzz commented on test/box-luatest/gh_10057_user_role_test.lua
> +
Let's check `box.schema.user.info()` here as well.

2025-06-11 21:24 UTC, drewdzzz commented on src/box/user.cc
> +	return false;
I would use BFS instead of DFS here:
1. I believe it's a good practice to beware of recursion.
2. It would be consistent with implementation of `role_check` function.

Function `role_check` is a good example of BFS implementation for privileges.

2025-06-23 10:41 UTC, mkostoevr commented on src/box/user.cc
> +	return false;
<details>

<summary>Right.</summary>

```diff
--- a/src/box/user.cc
+++ b/src/box/user.cc
@@ -917,15 +917,25 @@ role_is_granted(struct user *role, uint8_t auth_token)
                return true;
 
        /* Check if the role is granted transitively. */
-       struct user_map_iterator it;
-       user_map_iterator_init(&it, &role->users);
-       struct user *transitive_role;
-       while ((transitive_role = user_map_iterator_next(&it))) {
-               if (transitive_role->def->type == SC_ROLE &&
-                   role_is_granted(transitive_role, auth_token))
-                       return true;
+       struct user_map transitive_closure = user_map_nil;
+       struct user_map current_layer = user_map_nil;
+       user_map_union(&current_layer, &role->users);
+       while (!user_map_is_empty(&current_layer)) {
+               /*
+                * There's no loops in the role graph (this is guaranteed
+                * by the role_check), so we're are bound to end at some
+                * point in a layer with no incoming edges.
+                */
+               struct user_map next_layer = user_map_nil;
+               struct user_map_iterator it;
+               user_map_iterator_init(&it, &current_layer);
+               struct user *transitive_role;
+               while ((transitive_role = user_map_iterator_next(&it)))
+                       user_map_union(&next_layer, &transitive_role->users);
+               user_map_union(&transitive_closure, &next_layer);
+               current_layer = next_layer;
        }
-       return false;
+       return user_map_is_set(&transitive_closure, auth_token);
 }
 
 int
```

</details>

2025-06-23 10:42 UTC, mkostoevr commented on test/box-luatest/gh_10057_user_role_test.lua
> +
Seems redundant, it's tested above and implicitly tested here by selecting the `manager` role.

2025-07-16 09:33 UTC, drewdzzz commented on test/box-luatest/gh_10057_user_role_test.lua
> +
The user will call `box.schema.user.info()`, not `_vuser:select` - why not cover it with a test as well?

2025-07-16 09:41 UTC, drewdzzz approved these changes
Thank you for the patch, LGTM!

2025-07-18 10:01 UTC, sergepetrenko commented on test/box-luatest/gh_10057_user_role_test.lua
> +
I agree with @drewdzzz, the test shouldn't make such assumptions about internals (i.e. that covering `select` implicitly covers `box.schema.user.info()`).
Let's check `box.schema.user.info()` here as well.

2025-07-28 12:20 UTC, mkostoevr commented on test/box-luatest/gh_10057_user_role_test.lua
> +
<details>

<summary>diff</summary>

```diff
--- a/test/box-luatest/gh_10057_user_role_test.lua
+++ b/test/box-luatest/gh_10057_user_role_test.lua
@@ -33,7 +33,7 @@ g.test_user_role = function(cg)
         local original_user = box.session.effective_user()
         box.session.su('testuser')

-        -- Check we don't have a Lua error on box.schema.info().
+        -- Check we don't have a Lua error on box.schema.user.info().
         local ok = pcall(box.schema.user.info)
         t.assert(ok)

@@ -73,18 +73,26 @@ g.test_transitive_role = function(cg)

         -- Check the user has an access to the 'manager' role.
         t.assert_equals(#box.space._vuser.index.name:select('manager'), 1)
+        t.assert(pcall(box.schema.role.info, 'manager'))
+        t.assert(pcall(box.schema.user.info, 'testuser'))

         -- Check the user doesn't have access to the 'director' role.
         t.assert_equals(#box.space._vuser.index.name:select('director'), 0)
+        t.assert(not pcall(box.schema.role.info, 'director'))

         -- Check the user has an access to the 'management' role.
         t.assert_equals(#box.space._vuser.index.name:select('management'), 1)
+        t.assert(pcall(box.schema.role.info, 'management'))
+        t.assert(pcall(box.schema.role.info, 'manager'))

         -- Check the user doesn't have access to the 'infra' role.
         t.assert_equals(#box.space._vuser.index.name:select('infra'), 0)
+        t.assert(not pcall(box.schema.role.info, 'infra'))

         -- Check the user has an access to the 'staff' role.
         t.assert_equals(#box.space._vuser.index.name:select('staff'), 1)
+        t.assert(pcall(box.schema.role.info, 'staff'))
+        t.assert(pcall(box.schema.role.info, 'management'))

         box.session.su(original_user)
     end)
```

</details>

2025-07-29 11:53 UTC, merged