Added validate methods to space.format and tuple.format
tarantool/tarantool pull request #10965
Opened 2024-12-20 10:31 UTC by rorororom

feature: added validate methods to space.format and tuple.format
object

Added a validate method to box.tuple.format objects and
box.space._schema.format to directly check if a tuple conforms to
the format without needing to create a new tuple using box.tuple.new.

@TarantoolBot document
Title: Tuple and space format validate
Since: 3.4

To simplify tuple validation without the need for creating or inserting
a tuple, a new validate method is introduced for tuple format objects
and space formats.

Tuple Format Validation

A new validate method is added to tuple format objects, enabling the
validation of tuples or Lua tables against a defined format. This
method verifies that all fields in the tuple adhere to the type and
structure requirements specified in the format. If the tuple is invalid,
an error is raised.

The validate method works with both raw Lua tables and box.tuple objects.

Space Format Validation

Space formats now also support the validate method. The method operates
similarly to tuple format validation but uses the format of the associated
space.

Backward Compatibility

The existing approach of validating a tuple using box.tuple.new with a
format option remains unchanged. However, the new validate method
simplifies the process by removing the need to create a tuple explicitly
for validation purposes.

2024-12-20 19:30 UTC, lenkis approved these changes

2025-01-21 13:49 UTC, drewdzzz requested changes
The solution seems to be inappropriate since we have to re-implement tuple validation logic for Lua-tables.

I see two variants:
1. Implement solution suggested in the issue (replace `space.format` function with `tuple.format` Lua object). Such solution breaks backward compatibility. Also, we will lose a handy shortcut to set a format (`box.space.my_space:format(new_format)`) since it's won't be a function anymore.
2. Come up with a better solution. By the way, I have an idea. We could add a `box.space.my_space:validate(tuple)` (or `vilidate_tuple(tuple)`) so that we don't need to touch `box.space.my_space.format` at all.

2025-01-21 13:49 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +lbox_tuple_format_validate(lua_State *L)
Let's write a description: what the function does, what arguments it expects.

2025-03-24 09:34 UTC, rorororom commented on src/box/lua/tuple_format.c
> +lbox_tuple_format_validate(lua_State *L)
fix

2025-03-24 09:34 UTC, rorororom commented on src/box/lua/tuple_format.c
> +    struct tuple_format *format = *format_ptr;
fix

2025-04-16 08:19 UTC, drewdzzz requested changes

2025-04-16 08:19 UTC, drewdzzz commented on test/box-luatest/gh_9979_add_validate_function_for_space_test.lua
> +local t = require('luatest')
Please, extend the test in the old file.

2025-04-16 08:19 UTC, drewdzzz commented on test/box-luatest/gh_9979_add_validate_function_for_space_test.lua
> +        local space = box.schema.space.create('test_validate', {
I don't like how you replaced custom format with space format. Let's parametrize the test and cover both of them.

2025-04-18 13:21 UTC, rorororom commented on changelogs/unreleased/gh-9979-add-function-validate.md
> +* Added `validate` methods to `space.format` and `tuple.format` objects.
fixed

2025-04-18 13:25 UTC, rorororom commented on changelogs/unreleased/gh-9979-add-function-validate.md
fixed

2025-04-18 13:25 UTC, rorororom commented on test/box-luatest/gh_9979_add_validate_function_test.lua
> +local t = require('luatest')
fixed

2025-04-18 13:26 UTC, rorororom commented on test/box-luatest/gh_9979_add_validate_function_test.lua
> +    g.conn = net.connect(g.server.net_box_uri)
fixed

2025-04-18 13:26 UTC, rorororom commented on test/box-luatest/gh_9979_add_validate_function_test.lua
> +local net = require('net.box')
fixed

2025-04-18 13:27 UTC, rorororom commented on test/box-luatest/gh_9979_add_validate_function_test.lua
> +    local format = box.tuple.format.new({
fixed

2025-04-18 13:29 UTC, rorororom commented on src/box/lua/tuple_format.c
> +		luaL_checkudata(L, 1, tuple_format_typename);
fixed, used `luaT_check_tuple_format`

2025-04-18 13:29 UTC, rorororom commented on src/box/lua/tuple_format.c
> +	lua_pushboolean(L, true);
ok, fixed

2025-04-18 13:30 UTC, rorororom commented on test/box-luatest/gh_9979_add_validate_function_test.lua
> +    })
fixed, added new fields

2025-04-18 13:30 UTC, rorororom commented on test/box-luatest/gh_9979_add_validate_function_test.lua
> +        t.assert_error_msg_contains("expected string, got", function()
fixed

2025-04-18 13:32 UTC, rorororom commented on changelogs/unreleased/gh-9979-add-function-validate.md
> +* Added `space.format_object:validate(tuple)` method.
fixed

2025-04-18 13:34 UTC, rorororom commented on src/box/lua/tuple_format.c
> +#include "box/lua/tuple.h"
added this include for `luaT_tuple_new(L,…)`, `luaT_istuple(L,…)` and `luaT_checktuple(L,…)`

2025-04-18 13:35 UTC, rorororom commented on src/box/lua/space.cc
> +	luaL_getmetatable(L, "box.tuple.format");
fixed, `lbox_push_space_format_object` moved to `box/lua/tuple_format.c`

2025-04-18 13:36 UTC, rorororom commented on test/box-luatest/gh_9979_add_validate_function_for_space_test.lua
> +local t = require('luatest')
fixed

2025-04-18 13:36 UTC, rorororom commented on test/box-luatest/gh_9979_add_validate_function_for_space_test.lua
> +        local space = box.schema.space.create('test_validate', {
fixed

2025-04-21 07:14 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-add-function-validate.md
> What's about the second commit - why is there no title at all?

This part is not fixed.

2025-04-21 07:18 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-add-function-validate.md
> +* Added `validate` methods to `tuple.format` objects.
Please, follow our [developer guidelines](https://www.tarantool.io/en/doc/latest/contributing/release_notes/) when writing a changelog entry - issue reference is missing.

2025-04-21 08:05 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +		lua_pushnil(L);
Sysview spaces (like `_vspace`) have no format, though, one can obtain its format:
```lua
tarantool> box.space._space:format()
---
- [{'name': 'id', 'type': 'unsigned'}, {'name': 'owner', 'type': 'unsigned'}, {'name': 'name',
    'type': 'string'}, {'name': 'engine', 'type': 'string'}, {'name': 'field_count',
    'type': 'unsigned'}, {'name': 'flags', 'type': 'map'}, {'name': 'format', 'type': 'array'}]
...

tarantool> box.space._vspace:format()
---
- [{'name': 'id', 'type': 'unsigned'}, {'name': 'owner', 'type': 'unsigned'}, {'name': 'name',
    'type': 'string'}, {'name': 'engine', 'type': 'string'}, {'name': 'field_count',
    'type': 'unsigned'}, {'name': 'flags', 'type': 'map'}, {'name': 'format', 'type': 'array'}]
...
```

AFAICS from here, `box.space._vspace.format_object` will be `nil` and it will be inconsistent with `_vspace:format()`. It doesn't feel right for me.

2025-04-21 08:13 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
>  end
I've noticed that if one has no access to `space`, then `box.schema.space.format(space.id)` will fail. Hence, people without access cannot read format of a space. Unfortunately, the new feature will create a security breach since all spaces are still visible to all the users and everyone would see all the formats. I don't like it at all.

2025-04-21 08:15 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-add-function-validate.md
> +* Added `space.format_object:validate(tuple)` method.
No, it's not fixed. There is still one changelog for two features.

2025-04-21 08:18 UTC, drewdzzz commented on src/box/lua/tuple_format.h
> +lbox_push_space_format_object(struct lua_State *L, struct tuple_format *format);
I don't really like having a separate function for space format. It would be nice to have a function like `lbox_space_format_new_impl(struct lua_State *L, struct tuple_format *format)` that is just called from `lbox_space_tuple_new` and `lbox_fillspace`.

2025-04-21 08:28 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
>  end
Well, if one has access to Lua, he can do whatever he wants (`os.exit()`, for example). So that's not a security breach actually.

2025-04-21 11:50 UTC, rorororom commented on src/box/lua/tuple_format.c
> +		lua_pushnil(L);
However, in my current box implementation `box.space._vspace.format_object` is working correctly and returns the expected format, identical to what it returns `:format()`. Here is result:
```
tarantool> box.space._vspace.format_object
---
- [{'name': 'id', 'type': 'unsigned'}, {'name': 'owner', 'type': 'unsigned'}, {'name': 'name',
    'type': 'string'}, {'name': 'engine', 'type': 'string'}, {'name': 'field_count',
    'type': 'unsigned'}, {'name': 'flags', 'type': 'map'}, {'name': 'format', 'type': 'array'}]
...
```

2025-04-21 12:07 UTC, rorororom commented on src/box/lua/tuple_format.h
> +lbox_push_space_format_object(struct lua_State *L, struct tuple_format *format);
honestly, I didn't really understand your comment, so I decided to rename the function `lbox_push_space_format_object` in `lbox_space_format_new_impl`, now it looks more universal.

2025-04-21 12:10 UTC, rorororom commented on changelogs/unreleased/gh-9979-add-function-validate.md
> +* Added `tuple.format:validate(tuple)` and `space.format_object:validate(tuple)` methods.
Added a new `gh-9979-space-format-object.md`.

2025-04-21 12:11 UTC, rorororom commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                code = code,
fixed

2025-04-21 12:12 UTC, rorororom commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +            },
fixed
Added a new invalid case for checking array

2025-04-21 12:14 UTC, rorororom commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                {dict = {k = 'v'}}}),
fixed

2025-04-21 12:15 UTC, rorororom commented on changelogs/unreleased/gh-9979-add-function-validate.md
> +* Added `validate` methods to `tuple.format` objects.
fixed

2025-04-21 12:16 UTC, rorororom commented on changelogs/unreleased/gh-9979-add-function-validate.md
> +* Added `space.format_object:validate(tuple)` method.
Maybe fixed
I made two different changelogs.

2025-04-21 13:06 UTC, rorororom commented on changelogs/unreleased/gh-9979-add-function-validate.md
Сheck how it's done now, waiting for new edits)

2025-04-21 13:31 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                {dict = {k = 'v'}}}),
Well, it's partially fixed - you didn;t drop tuples from `valid_cases`.

2025-04-21 13:44 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-tuple-format-validate.md
> -* Now `tuple.format` objects have a `validate(tuple)` method to verify tuple data against the defined format (gh-9979).
Why did you drop this changelog?

2025-04-21 13:44 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +* Now `box.space` objects have a `format_object` property to provide access to their tuple format (gh-9979).
Limit for changelog line length is 75 symbols.

2025-04-21 13:44 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +		lua_pushnil(L);
Hm, you are right. Anyway, why do you check for `NULL` here? Are there cases when the format is `NULL`?

2025-04-21 13:48 UTC, rorororom commented on src/box/lua/tuple_format.c
> +		lua_pushnil(L);
Maybe someday there will be a space without a fixed format.

2025-04-21 13:49 UTC, rorororom commented on src/box/lua/tuple_format.c
> +		lua_pushnil(L);
I need to think about whether there are cases when the format is null.

2025-04-21 13:56 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +		lua_pushnil(L);
But format object is serialized as an empty table here, not nil:
```lua
tarantool> box.schema.space.create('foo')
---
- format_object: []
 ...
```

2025-04-21 14:04 UTC, rorororom commented on src/box/lua/tuple_format.c
> +		lua_pushnil(L);
Maybe then it should be removed....

2025-04-21 14:39 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +		lua_pushnil(L);
After commit https://github.com/tarantool/tarantool/commit/5072227e79334593e675f55a8dd12e0fdce45238 spaces cannot have `NULL` format. Let's add a separate commit that adds an assertion to `space_create` that `format` is not `NULL` and removes all the format checks. After that, we can remove this check since `space->format` couldn't be `NULL` officially.

2025-04-21 14:45 UTC, drewdzzz requested changes

2025-04-21 14:45 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-tuple-format-validate.md
> +## feature/box
Title in doc request: `Title: Tuple and space format validate`
There is no space format in this commit.

2025-04-21 14:45 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +## feature/box
Regarding commit message:

> `format_object` creates references to `tuple_format` for space object
via `tuple_format_ref`. These references can be held by spaces remaining
in memory (for example, in the global `box.space` table), especially if
other tests create spaces.

The sentence shouldn't start from name of a field, because that implies a small letter, and starting a sentence from a small letter is not convenient.

2025-04-21 14:45 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +## feature/box
The same about doc request:

> `format_object` method returns a `box.tuple.format` object associated
with the space's format. This object provides the same methods as
`box.tuple.format`, including method `validate`.

2025-04-21 14:45 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +## feature/box
What's the example about?!

> Example:
```lua
space = box.schema.space.create('test', {
    format = {
        {name = 'id', type = 'unsigned'},
        {name = 'name', type = 'string'}
    }
})
```

2025-04-21 14:45 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +## feature/box
> Title: Tuple and space format validate

The commit is about a new field `format_object` in `space`.

2025-04-21 14:46 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +		return luaL_error(L, "Expected tuple or table");
Please, cover all the errors with tests. (Possible ones, at least).

2025-04-21 14:48 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +        local s = box.schema.space.create('test_fmt_obj', {
Let's call the space `test`, and let's drop it in `after_test` hook (or `after_each`).

2025-04-21 14:53 UTC, drewdzzz commented on src/box/lua/tuple_format.h
> +lbox_push_space_format_object(struct lua_State *L, struct tuple_format *format);
I meant, it would be nice to have `lbox_space_format_new_impl` to call it from `lbox_space_format_new` and `lbox_fillspace` in order to avoid code duplication.

2025-04-23 13:18 UTC, rorororom commented on changelogs/unreleased/gh-9979-tuple-format-validate.md
> +## feature/box
fixed

2025-04-23 13:22 UTC, rorororom commented on changelogs/unreleased/gh-9979-space-format-object.md
> +## feature/box
fixed

2025-04-23 13:23 UTC, rorororom commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                {dict = {k = 'v'}}}),
fixed

2025-04-23 15:38 UTC, rorororom commented on src/box/lua/tuple_format.c
> +		return luaL_error(L, "Expected tuple or table");
added `g.test_format_validate_usage_error`

2025-04-24 20:36 UTC, drewdzzz requested changes
Thank you for your work! I left a bunch of comments, also:
1. Please, use `Closes #xxx` only in the last commit. You can write `Part of #xxx` in other commits.
2. Please, update all the doc requests: `Since: 3.4` -> `Since: 3.5` - Tarantool 3.4 was released recently, so this feature will appear only in Tarantool 3.5.
3. We forgot about `net.box`! It also has its `space` objects that imitate behavior of `box.space`. Please, populate them with `format_object` field too. It is gonna be very easy since they are written in pure Lua (`src/box/lua/net_box.lua`).

2025-04-24 20:36 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                'Expected tuple or table',
I don't get it. How does this test work if you throw another error?!
```c
	if (luaT_istuple(L, 2)) {
		tuple = luaT_checktuple(L, 2);
	} else if (lua_istable(L, 2)) {
		tuple = luaT_tuple_new(L, 2, format);
		if (tuple == NULL)
			return luaT_error(L);
	} else {
		return luaL_error(L, "Usage: format:validate(tuple_or_table)");
	}
```

2025-04-24 20:36 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +## feature/box
Doc request:
`Title: Add method format_object to box.space`
Method is a function. That's not a function, hence, not a method :)
Please, use word `field` instead.

Also, in doc request:
```
format = space:format_objectt
```
Shouldn't it be `format = space.format_object`?!
Also, let's use the field directly: `space.format_object:validate({123, 'example'})`.
Also, let's remove the comment `-- this gives space the validate method` - that's clear from the example :)

2025-04-24 20:36 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +* Now `box.space.format_object` property to access tuple format (gh-9979).
That's not a valid sentence according to English grammar. I suggest:
```
Populated `box.space` objects with the new field `format_object` (gh-9979).
```

2025-04-24 20:36 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +		return luaL_error(L, "Expected tuple or table");
Please, drop this change.

2025-04-24 20:36 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> -		return luaL_error(L, "Invalid tuple format");
Let's leave this check here. Anyway, this change doesn't belong to this commit.

2025-04-24 20:36 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +	luaL_setmetatable(L, tuple_format_typename);
That doesn't right - Lua methods may throw (the function will exit immediately with an underlying `jmp` instruction). Then, the reference will become dangling and it will result in a memory leak. So the format should be referenced only after the allocation and setting the metatable.

2025-04-24 20:36 UTC, drewdzzz commented on src/box/lua/tuple_format.h
> + * Stack: Output is box.tuple.format userdata or nil if format is NULL.
Format cannot be `NULL`.

2025-04-27 12:17 UTC, rorororom commented on src/box/space.c
> +
fixed

2025-04-27 12:17 UTC, rorororom commented on src/box/space.c
> +
fixed

2025-04-27 12:18 UTC, rorororom commented on src/box/space.c
>  	trigger_destroy(&space->on_replace);
I've removed several checks (which ones i noticed).

2025-04-27 12:18 UTC, rorororom commented on src/box/space.c
> +	assert(format != NULL);
fixed

2025-04-27 12:18 UTC, rorororom commented on changelogs/unreleased/gh-9979-tuple-format-validate.md
> +* Now `box.tuple.format:validate()` validates tuple data (gh-9979).
fixed

2025-04-27 12:19 UTC, rorororom commented on changelogs/unreleased/gh-9979-tuple-format-validate.md
> +## feature/box
fixed

2025-04-27 12:20 UTC, rorororom commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                'Expected tuple or table',
Change error
(There must be a mistake "Expected tuple or table").

2025-04-27 12:20 UTC, rorororom commented on changelogs/unreleased/gh-9979-space-format-object.md
> +## feature/box
fixed

2025-04-27 12:20 UTC, rorororom commented on changelogs/unreleased/gh-9979-space-format-object.md
> +* Now `box.space.format_object` property to access tuple format (gh-9979).
fixed

2025-04-27 12:21 UTC, rorororom commented on src/box/lua/tuple_format.c
> +		return luaL_error(L, "Expected tuple or table");
I registered the correct error.

2025-04-27 12:21 UTC, rorororom commented on src/box/lua/tuple_format.c
> -		return luaL_error(L, "Invalid tuple format");
fixed

2025-04-27 12:22 UTC, rorororom commented on src/box/lua/tuple_format.c
> +	luaL_setmetatable(L, tuple_format_typename);
fixed

2025-04-27 12:22 UTC, rorororom commented on src/box/lua/tuple_format.h
> + * Stack: Output is box.tuple.format userdata or nil if format is NULL.
fixed

2025-04-27 13:56 UTC, drewdzzz requested changes
What's about `net.box`? (See [this comment](https://github.com/tarantool/tarantool/pull/10965#pullrequestreview-2792319395), pt. 3)

2025-04-27 13:56 UTC, drewdzzz commented on src/box/alter.cc
> -	if (format == NULL)
You shouldn't drop this check...
It checks that decode was successful.

2025-04-27 13:56 UTC, drewdzzz commented on src/box/space.h
> +	 * Space format.
Please, write here that it cannot be `NULL`.

Space in Lua can have no format, so it can lead to confusion - let's note that it cannot be `NULL` here.

2025-04-27 13:56 UTC, drewdzzz commented on src/box/alter.cc
> +	is_min_field_count_changed = old_space->format->min_field_count !=
It was under `else` condition before your commit.

2025-04-27 13:56 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +	lbox_space_format_new_impl(L, format);
That's not the way. There is even a comment saying that you shouldn't call any Lua helpers after you've created a format and before you've referenced it.

Maybe, we should factor `lbox_space_format_new_impl` out in a different way?

2025-04-27 13:59 UTC, drewdzzz commented on src/box/alter.cc
> -
Let's leave an extra space here, like it was before the commit.

2025-04-27 16:50 UTC, rorororom commented on src/box/alter.cc
> -	if (format == NULL)
fixed

2025-04-27 16:50 UTC, rorororom commented on src/box/alter.cc
> +	is_min_field_count_changed = old_space->format->min_field_count !=
fixed

2025-04-27 16:51 UTC, rorororom commented on src/box/alter.cc
> -
fixed

2025-04-27 16:51 UTC, rorororom commented on src/box/space.h
> +	 * Space format.
fixed

2025-04-27 16:54 UTC, rorororom commented on src/box/lua/tuple_format.c
> +	lbox_space_format_new_impl(L, format);
Now, no Lua helpers are called before tuple_format_ref.

2025-04-28 10:15 UTC, drewdzzz requested changes

2025-04-28 10:15 UTC, drewdzzz commented on src/box/space.h
> +	 * Space format.
`this field is guaranteed non-NULL.`
That's not right sentence according to English grammar. Also, let's make it shorter, like:
```c
/**
 * Space format, cannot be NULL.
 */
```

2025-04-28 10:15 UTC, drewdzzz commented on src/box/space.h
> +	 * Space format.
Also, this change doesn't belong to this commit...

2025-04-28 10:15 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +    conn:close()
The test is about `net.space.format_obect`. Why do you use `eval` here?

2025-04-28 10:15 UTC, drewdzzz commented on src/box/lua/tuple_format.h
> + * Stack: Output is box.tuple.format userdata.
The description is outdated.

Also, please mention here, that the created tuple format object is guaranteed to contain `NULL`.

2025-04-28 10:15 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +		(struct tuple_format **)lua_newuserdata(L, sizeof(*pf));
Please, set `*pf` to `NULL`, just like it was before your commit.

2025-04-28 10:15 UTC, drewdzzz commented on src/box/lua/space.cc
> +	struct tuple_format **pf = lbox_space_format_new_impl(L);
Let's use `format_ptr` for variable name.

2025-04-28 10:15 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +	struct tuple_format **pf =
Why did you rename `format_ptr` to `pf`?

2025-04-28 10:15 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +		(struct tuple_format **)lua_newuserdata(L, sizeof(*pf));
Also, let's use `format_ptr` name here as well - it seems nicer.

2025-04-28 10:15 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +* Populated `box.space` objects with the new field `format_object` (gh-9979).
You've just populated `space` objects of `net.box` with `format_object` as well. Please, write about them in your:
1. Commit message.
2. Doc request.
3. Changelog entry.

2025-05-02 14:11 UTC, rorororom commented on src/box/lua/space.cc
> +	struct tuple_format **pf = lbox_space_format_new_impl(L);
fixed

2025-05-02 14:11 UTC, rorororom commented on src/box/lua/tuple_format.c
> +		(struct tuple_format **)lua_newuserdata(L, sizeof(*pf));
fixed

2025-05-02 14:11 UTC, rorororom commented on src/box/lua/tuple_format.h
> + * Stack: Output is box.tuple.format userdata.
fixed

2025-05-02 14:12 UTC, rorororom commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +    conn:close()
fixed

2025-05-05 14:13 UTC, drewdzzz requested changes
Thanks for the fixes, we are almost done!

2025-05-05 14:13 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +            {'json1', require('json').decode('{"x":1}'), 10, {'json'},
Nit: why do you need  `require('json').decode('{"x":1}')` here? Just pass `{x = 1}`.

2025-05-05 14:13 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                value    = {1, 'value', 1, {}, {}},
Too many whitespaces.

2025-05-05 14:13 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                field    = 4, name = 'tags',
Again, please drop these whitespaces.

2025-05-05 14:13 UTC, drewdzzz commented on src/box/lua/net_box.lua
> +
Wow, that's pretty complicated. Doesn't just a format object work here?

2025-05-05 14:13 UTC, drewdzzz commented on src/box/lua/tuple_format.c
> +		(struct tuple_format **)lbox_space_format_new_impl(L);
Nit: you don't need this cast.

2025-05-05 20:42 UTC, rorororom commented on src/box/lua/net_box.lua
> +
If use `tuple_format.new(..., true)`, then `names_only` mode is used  (that is, no error is displayed, validate does not work in principle), and if `tuple_format.new(..., false)`, then collation may not be in `net_box `(several tests failed).

So I implemented it through a proxy via `conn:eval(...)`.

2025-05-05 20:43 UTC, rorororom commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                field    = 4, name = 'tags',
fixed

2025-05-05 20:43 UTC, rorororom commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                value    = {1, 'value', 1, {}, {}},
fixed

2025-05-05 20:44 UTC, rorororom commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +            {'json1', require('json').decode('{"x":1}'), 10, {'json'},
You're right. Fixed

2025-05-05 20:45 UTC, rorororom commented on src/box/lua/tuple_format.c
> +		(struct tuple_format **)lbox_space_format_new_impl(L);
You're right. Fixed

2025-05-12 06:33 UTC, drewdzzz requested changes

2025-05-12 06:33 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +            {'json1', require('json').decode('{"x":1}'), 10, {'json'},
You've fixed it in another commit - please move the fix to the appropriate one.

2025-05-12 06:33 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                value    = {1, 'value', 1, {}, {}},
You've fixed it in another commit - please move the fix to the appropriate one.

2025-05-12 06:33 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                field    = 4, name = 'tags',
You've fixed it in another commit - please move the fix to the appropriate one.

2025-05-12 06:33 UTC, drewdzzz commented on src/box/lua/net_box.lua
> +
> and if `tuple_format.new(..., false)`, then collation may not be in `net_box` (several tests failed).

I don't understand, what caused the failure. Could you, please, share some test failure logs to make it more clear?

2025-05-12 13:58 UTC, rorororom commented
The implementation of format_object for space in net_box has been removed, the reason is written in the pr comment.

2025-05-14 08:36 UTC, drewdzzz requested changes
Looks great! Let's just add one more test case and fix some wordings, and I'll approve the patch!

2025-05-14 08:36 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +## feature/box
> Implementation note:
The format_object method was not implemented for net.box spaces:
>1. Remote verification will require sending tuples over the network;
>2. May fail when format references collations or types unavailable
on client.

1. `format_object` is not a method.
2. Let's remove this `Implementation note` line (the whole commit message is an implementation note, actually). And let's put this information before test adjustments.
3. "May fail when format references collations or types unavailable on client." - It's not clear, what may fail.

2025-05-14 08:36 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +space in `net.box` with the same `format_object` field (gh-9979).
Spaces from `net.box` are not populated anymore.

2025-05-14 08:36 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +## feature/box
`box.space` is actually Lua storage of all spaces:
```lua
tarantool> box.space
---
- test2:
    is_local: false
    is_sync: false
    temporary: false
    engine: memtx
  test1:
    is_local: false
    is_sync: false
    temporary: false
    engine: memtx
...
```

So let's use just space instead of `box.space` in changelog, doc request and commit message to avoid confusion.

2025-05-14 08:36 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +                format.validate, format, bad
Let's also add a case when we pass an invalid object instead of the `format` itself.

2025-05-15 07:35 UTC, drewdzzz requested changes
A few nitpicks.
Please, do not forget to answer my comments and re-request the review.

2025-05-15 07:35 UTC, drewdzzz commented on changelogs/unreleased/gh-9979-space-format-object.md
> +## feature/box
You didn't update the changelog.

2025-05-15 07:35 UTC, drewdzzz commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +
This change doesn't belong to this commit...

2025-05-15 10:07 UTC, rorororom commented on test/box-luatest/gh_9979_tuple_format_validate_test.lua
> +
You're right, my mistake has been fixed.

2025-05-15 10:09 UTC, rorororom commented on changelogs/unreleased/gh-9979-space-format-object.md
> +## feature/box
fixed

2025-05-16 13:21 UTC, locker commented on src/box/lua/tuple_format.c
> +		return luaL_error(L, "Invalid tuple format");
This check is redundant - `luaT_check_tuple_format` throws an error on failure.

2025-05-16 13:35 UTC, locker commented on src/box/lua/space.cc
> +	*format_ptr = space->format;
Instead of `lbox_space_format_new_impl`, better add `luaT_push_tuple_format` that would take a pointer to `tuple_format`, take a reference to it, and push it to the Lua stack, similarly to `luaT_push_key_def`.

2025-05-16 16:38 UTC, rorororom commented on src/box/lua/space.cc
> +	*format_ptr = space->format;
I’d prefer not to hide the `tuple_format_ref()` inside `luaT_push_tuple_format()`, since taking a reference too early (before metatable setup or error-prone Lua code) may lead to leaks. It’s safer to split allocation and referencing explicitly to keep `gc` and ownership clear.

Correct me if I'm wrong.

2025-05-16 16:39 UTC, rorororom commented on src/box/lua/tuple_format.c
> +		return luaL_error(L, "Invalid tuple format");
fixed

2025-05-19 08:36 UTC, locker commented on src/box/lua/space.cc
> +	*format_ptr = space->format;
You could define `luaT_push_tuple_format` as:

```C
void
luaT_push_tuple_format(struct lua_State *L, struct tuple_format *format)
{
	struct tuple_format **format_ptr = lua_newuserdata(L, sizeof(*format_ptr));
	*format_ptr = NULL;
	luaL_getmetatable(L, tuple_format_typename);
	lua_setmetatable(L, -2);
	tuple_format_ref(format);
	*format_ptr = format;
}
```

Then it wouldn't be error prone AFAICS. There's no need to reuse this function in `lbox_tuple_format_new` BTW.

2025-05-19 09:26 UTC, rorororom commented on src/box/lua/space.cc
> +	*format_ptr = space->format;
hm, okay, fixed

2025-05-19 10:12 UTC, locker approved these changes

2025-05-26 11:32 UTC, lenkis approved these changes

2025-05-26 11:32 UTC, lenkis commented on changelogs/unreleased/gh-9979-space-format-object.md
> +* Populated space objects with the new `format_object` field (gh-9979).
```suggestion
* Populated space objects with a new field `format_object` (gh-9979).
```

2025-05-26 11:32 UTC, lenkis commented on changelogs/unreleased/gh-9979-tuple-format-validate.md
> +* Populated `box.tuple.format` objects with the new method `validate` (gh-9979).
```suggestion
* Populated `box.tuple.format` objects with a new method `validate` (gh-9979).
```

2025-05-27 11:19 UTC, merged