cmake: support TAP tests by CTest
tarantool/tarantool pull request #11004
Opened 2024-12-26 12:39 UTC by ligurio

2025-03-03 12:52 UTC, ligurio commented
(rebased to the master branch)

2025-03-04 14:55 UTC, Buristan requested changes
Hi, Sergey!
Thanks for the patch-set and decent work regarding this activity!
Very appreciate the fact that we may run tests much more simply.
I'll proceed with the review per-patch below.

---

**[PATCH 1/4] test: remove suite.cfg in box-tap**

LGTM!

---

**[PATCH 2/4] test: update parameters in sql-tap tests**

LGTM, with a minor nits regarding the commit message.

> Long time ago (as Mergen Imeev told) API for Tarantool's storage

Typo: s/Long/A long/
Typo: s/told)/told),/

> engines was not unified and SQL tests can be successfully executed

Typo: s/unified/unified,/
Typo: s/can/could/

> on one engine and be broken on other. Due to this, some SQL tests

Typo: s/other/another/

---

**[PATCH 3/4] cmake: define test parameter delimiter**

LGTM.

---

**[PATCH 4/4] cmake: support TAP tests by CTest**

Generally LGTM, but see several suggestions and comments below.

> Note, that TAP test suites uses environment variable

Typo: s/uses/use
Typo: s/environment/the environment/

> `MEMTX_ALLOCATOR`. Support from test executor is not required for

Typo: s/test executor/the test executor/

> files, in parallel corrupts generated Lua files.

Typo: s/files,/files/
Typo: s/generated/the generated/

I saw that we have very similar prologues and epilogues for each of the TAP/luatest suites:
Prologue:
```
  get_filename_component(test_name ${test_path} NAME)
  # FIXME: By default, GLOB lists directories.
  # Directories are omitted in the result if LIST_DIRECTORIES
  # is set to false. New in version CMake 3.3.
  if(${test_name} STREQUAL ${TEST_SUITE_NAME})
    continue()
  endif()
  set(test_title "test/${TEST_SUITE_NAME}/${test_name}")
```

Epilogue:
```
  set_tests_properties(${test_title} PROPERTIES
    ENVIRONMENT "${TEST_ENV}"
    LABELS "${TEST_SUITE_NAME};regression;"
    DEPENDS ${TEST_SUITE_NAME}-deps
    FAIL_REGULAR_EXPRESSION "${CTEST_FAIL_REGEXP}"
  )
```

Maybe we can somehow use a macro for these parts to avoid copy-pasting with errors (see the comment below `integration` vs `regression` label).

Also, the bodies of the test setup are similar across the suites (i.e., for all luatest/for all TAP suites).
And the same note is about setup for different engines. The setup is literally the same except for the engine name.

What do you think about this macro approach?
Feel free to ignore, though.

Also, I've got tons of SQL test failed runs from the root project dir like the following:
```
$ ctest -V -R test/sql-tap/alter2.test.lua:memtx
...
1442: Got     : [1,"Failed to create foreign key constraint 'fk2': referenced space doesn't feature PRIMARY KEY"]
```

2025-03-04 14:55 UTC, Buristan commented on test/app-tap/CMakeLists.txt
> +    ${CMAKE_CURRENT_SOURCE_DIR}/lua/?.lua
Please add a comment what auto-generated file should be placed in those directories.

2025-03-04 14:55 UTC, Buristan commented on test/app-tap/CMakeLists.txt
> +           WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
Q: Should it be also `${work_dir}` for the consistency?
Here and below.

2025-03-04 14:55 UTC, Buristan commented on test/app-tap/CMakeLists.txt
> +    LABELS "${TEST_SUITE_NAME};integration"
Looks like a typo: should it be `regression`, like in all luatest suites and etc.?
Here and below.

2025-03-04 14:55 UTC, Buristan commented on test/app-tap/CMakeLists.txt
> +    test/app-tap/console.test.lua
This condition disables it for Linux too, I've got the following message locally:
```
 The following tests did not run:
         795 - test/app-tap/console.test.lua (Disabled)
```

2025-03-04 14:55 UTC, Buristan commented on test/box-tap/CMakeLists.txt
> +  if(NOT ${test_title} STREQUAL test/box-tap/cfg.test.lua AND
Q: Why do we avoid the `TT_WORK_DIR` for these tests?
Please add the comment.

2025-03-04 14:55 UTC, Buristan commented on test/engine-tap/CMakeLists.txt
> +    ENVIRONMENT "${TEST_ENV};TT_WORK_DIR=${work_dir};TEST_ENGINE=vinyl;"
Why do we have `;` at the end here but not for the memtx setup?

2025-03-04 14:55 UTC, Buristan commented on test/engine-tap/lib/tester.lua
> +               os.getenv('TEST_ENGINE')
I suppose this should be `os.getenv('TEST_ENGINE') or 'memtx'` to remain the compatibility with test_run.

2025-03-04 14:55 UTC, Buristan commented on test/engine-tap/lib/tester.lua
> +engine = engine:gsub('"', '')
Why do we need this line? Looks like CMake misconfiguration.

2025-03-04 14:55 UTC, Buristan commented on test/sql-tap/CMakeLists.txt
> +string(JOIN ";" DISABLED_TESTS
Minor: Why don't use `list(APPEND` instead?

2025-03-04 14:55 UTC, Buristan commented on test/sql-tap/CMakeLists.txt
> +# See test/sql-tap/suite.ini.
Since #11043 is landed, should the part below be deleted?

2025-03-04 14:55 UTC, Buristan commented on test/sql-tap/lua/sqltester.lua
> +               os.getenv('TEST_ENGINE')
I suppose this should be `os.getenv('TEST_ENGINE') or 'memtx'` to remain the compatibility with test_run.

2025-03-05 09:44 UTC, ligurio commented on test/engine-tap/CMakeLists.txt
> +    ENVIRONMENT "${TEST_ENV};TT_WORK_DIR=${work_dir};TEST_ENGINE=vinyl;"
It was excess, removed.

```diff
--- a/test/app-tap/CMakeLists.txt
+++ b/test/app-tap/CMakeLists.txt
@@ -58,7 +58,7 @@ foreach(test_path ${tests})
     list(APPEND TEST_ENV_VARS TT_WORK_DIR=${work_dir})
   endif()
   set_tests_properties(${test_title} PROPERTIES
-    ENVIRONMENT "${TEST_ENV};${TEST_ENV_VARS};"
+    ENVIRONMENT "${TEST_ENV};${TEST_ENV_VARS}"
     LABELS "${TEST_SUITE_NAME};integration"
     DEPENDS ${TEST_SUITE_NAME}-deps
     FAIL_REGULAR_EXPRESSION "${CTEST_FAIL_REGEXP}"
``

2025-03-05 09:47 UTC, ligurio commented on test/sql-tap/CMakeLists.txt
> +string(JOIN ";" DISABLED_TESTS
Fixed:

```diff
--- a/test/sql-tap/CMakeLists.txt
+++ b/test/sql-tap/CMakeLists.txt
@@ -84,7 +84,7 @@ foreach(test_path ${tests})
 endforeach()
 
 # See test/sql-tap/suite.ini.
-string(JOIN ";" DISABLED_TESTS
+list(APPEND DISABLED_TESTS
   test/sql-tap/analyze1.test.lua
   test/sql-tap/analyze3.test.lua
   test/sql-tap/analyze4.test.lua
```

2025-03-05 15:18 UTC, ligurio commented on test/sql-tap/CMakeLists.txt
> +# See test/sql-tap/suite.ini.
Many thanks!

```diff
@@ -116,17 +116,3 @@ foreach(test_name IN LISTS DISABLED_TESTS)
     PROPERTIES DISABLED TRUE
   )
 endforeach()
-
-# See test/sql-tap/suite.ini.
-string(JOIN ";" LONG_TESTS
-  test/sql-tap/gh-3332-tuple-format-leak.test.lua
-  test/sql-tap/gh-3083-ephemeral-unref-tuples.test.lua
-)
-foreach(test_name IN LISTS LONG_TESTS)
-  set_tests_properties(
-    ${test_name}${TEST_PARAM_DELIM}memtx
-    ${test_name}${TEST_PARAM_DELIM}vinyl
-    PROPERTIES
-      LABELS "long"
-  )
-endforeach()
```

2025-03-05 15:36 UTC, Buristan commented
> Also, I've got tons of SQL test failed runs from the root project dir like the following:

PEBKAC, I've cleaned the CMake flags related to fuzzing. Ignore this part.

2025-03-05 15:36 UTC, ligurio commented on test/app-tap/CMakeLists.txt
> +    LABELS "${TEST_SUITE_NAME};integration"
```
[1] ~/sources/MRG/tarantool $ find test/*-tap -name CMakeLists.txt |xargs grep LABELS
test/app-tap/CMakeLists.txt:  LABELS ${TEST_SUITE_NAME}
test/app-tap/CMakeLists.txt:    LABELS "${TEST_SUITE_NAME};integration"
test/box-tap/CMakeLists.txt:  LABELS ${TEST_SUITE_NAME}
test/box-tap/CMakeLists.txt:    LABELS "${TEST_SUITE_NAME};integration"
test/engine-tap/CMakeLists.txt:  LABELS ${TEST_SUITE_NAME}
test/engine-tap/CMakeLists.txt:    LABELS "${TEST_SUITE_NAME};integration"
test/engine-tap/CMakeLists.txt:    LABELS "${TEST_SUITE_NAME};integration"
test/sql-tap/CMakeLists.txt:  LABELS ${TEST_SUITE_NAME}
test/sql-tap/CMakeLists.txt:    LABELS "${TEST_SUITE_NAME};integration"
test/sql-tap/CMakeLists.txt:    LABELS "${TEST_SUITE_NAME};integration"
```

Right, fixed:

```diff
diff --git a/test/app-tap/CMakeLists.txt b/test/app-tap/CMakeLists.txt
index c214136903..837c2b1194 100644
--- a/test/app-tap/CMakeLists.txt
+++ b/test/app-tap/CMakeLists.txt
@@ -59,7 +59,7 @@ foreach(test_path ${tests})
   endif()
   set_tests_properties(${test_title} PROPERTIES
     ENVIRONMENT "${TEST_ENV};${TEST_ENV_VARS}"
-    LABELS "${TEST_SUITE_NAME};integration"
+    LABELS "${TEST_SUITE_NAME};regression"
     DEPENDS ${TEST_SUITE_NAME}-deps
     FAIL_REGULAR_EXPRESSION "${CTEST_FAIL_REGEXP}"
   )
diff --git a/test/box-tap/CMakeLists.txt b/test/box-tap/CMakeLists.txt
index d42a9e202a..f9808401ef 100644
--- a/test/box-tap/CMakeLists.txt
+++ b/test/box-tap/CMakeLists.txt
@@ -48,7 +48,7 @@ foreach(test_path ${tests})
   endif()
   set_tests_properties(${test_title} PROPERTIES
     ENVIRONMENT "${TEST_ENV_VARS}"
-    LABELS "${TEST_SUITE_NAME};integration"
+    LABELS "${TEST_SUITE_NAME};regression"
     DEPENDS ${TEST_SUITE_NAME}-deps
     FAIL_REGULAR_EXPRESSION "${CTEST_FAIL_REGEXP}"
   )
diff --git a/test/engine-tap/CMakeLists.txt b/test/engine-tap/CMakeLists.txt
index e85fa03ce3..33cd702eb6 100644
--- a/test/engine-tap/CMakeLists.txt
+++ b/test/engine-tap/CMakeLists.txt
@@ -36,7 +36,7 @@ foreach(test_path ${tests})
   )
   set_tests_properties(${test_title} PROPERTIES
     ENVIRONMENT "${TEST_ENV};TT_WORK_DIR=${work_dir};TEST_ENGINE=memtx"
-    LABELS "${TEST_SUITE_NAME};integration"
+    LABELS "${TEST_SUITE_NAME};regression"
     DEPENDS ${TEST_SUITE_NAME}-deps
     FAIL_REGULAR_EXPRESSION "${CTEST_FAIL_REGEXP}"
   )
@@ -51,7 +51,7 @@ foreach(test_path ${tests})
   )
   set_tests_properties(${test_title} PROPERTIES
     ENVIRONMENT "${TEST_ENV};TT_WORK_DIR=${work_dir};TEST_ENGINE=vinyl;"
-    LABELS "${TEST_SUITE_NAME};integration"
+    LABELS "${TEST_SUITE_NAME};regression"
     DEPENDS ${TEST_SUITE_NAME}-deps
     FAIL_REGULAR_EXPRESSION "${CTEST_FAIL_REGEXP}"
   )
diff --git a/test/sql-tap/CMakeLists.txt b/test/sql-tap/CMakeLists.txt
index a31689653f..5d1dc1878f 100644
--- a/test/sql-tap/CMakeLists.txt
+++ b/test/sql-tap/CMakeLists.txt
@@ -62,7 +62,7 @@ foreach(test_path ${tests})
   )
   set_tests_properties(${test_title} PROPERTIES
     ENVIRONMENT "${TEST_ENV};TT_WORK_DIR=${work_dir};TEST_ENGINE=memtx;"
-    LABELS "${TEST_SUITE_NAME};integration"
+    LABELS "${TEST_SUITE_NAME};regression"
     DEPENDS ${TEST_SUITE_NAME}-deps
     FAIL_REGULAR_EXPRESSION "${CTEST_FAIL_REGEXP}"
   )
@@ -77,7 +77,7 @@ foreach(test_path ${tests})
   )
   set_tests_properties(${test_title} PROPERTIES
     ENVIRONMENT "${TEST_ENV};TT_WORK_DIR=${work_dir};TEST_ENGINE=vinyl;"
-    LABELS "${TEST_SUITE_NAME};integration"
+    LABELS "${TEST_SUITE_NAME};regression"
     DEPENDS ${TEST_SUITE_NAME}-deps
     FAIL_REGULAR_EXPRESSION "${CTEST_FAIL_REGEXP}"
   )
```

2025-03-05 17:27 UTC, ligurio commented on test/app-tap/CMakeLists.txt
> +    test/app-tap/console.test.lua
Replaced with condition with `CMAKE_SYSTEM_NAME` [^1].

```diff
--- a/test/app-tap/CMakeLists.txt
+++ b/test/app-tap/CMakeLists.txt
@@ -74,7 +74,7 @@ if(NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
 endif()
 
 # See console.skipcond, disabled on FreeBSD due to fail #4271.
-if(UNIX AND NOT APPLE)
+if(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
   set_tests_properties(
     test/app-tap/console.test.lua
     PROPERTIES DISABLED TRUE
```

[^1]: https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_NAME.html

2025-03-05 17:32 UTC, ligurio commented on test/box-tap/CMakeLists.txt
> +  if(NOT ${test_title} STREQUAL test/box-tap/cfg.test.lua AND
Added:

```diff
--- a/test/box-tap/CMakeLists.txt
+++ b/test/box-tap/CMakeLists.txt
@@ -42,6 +42,8 @@ foreach(test_path ${tests})
   # - test/box-tap/auth.test.lua
   # - test/box-tap/extended_error.test.lua
   set(TEST_ENV_VARS "${TEST_ENV};LISTEN=${work_dir}/listen.sock;")
+  # The tests below could be broken by setting environment
+  # variable `TT_WORK_DIR`, so `TT_WORK_DIR` is not set.
   if(NOT ${test_title} STREQUAL test/box-tap/cfg.test.lua AND
      NOT ${test_title} STREQUAL test/box-tap/gh-4562-errno-at-xdir_scan.test.lua)
     set(TEST_ENV_VARS ${TEST_ENV_VARS};TT_WORK_DIR=${work_dir};)
```

2025-03-05 17:35 UTC, ligurio commented on test/engine-tap/lib/tester.lua
> +engine = engine:gsub('"', '')
It is not needed actually, removed:

```diff
--- a/test/engine-tap/lib/tester.lua
+++ b/test/engine-tap/lib/tester.lua
@@ -12,7 +12,6 @@ local ok, test_run = pcall(require, 'test_run')
 test_run = ok and test_run.new() or nil
 local engine = test_run ~= nil and test_run:get_cfg('engine') or
                os.getenv('TEST_ENGINE')
-engine = engine:gsub('"', '')
 
 function test.engine(self)
     return engine
```

2025-03-05 17:44 UTC, Buristan commented on test/app-tap/CMakeLists.txt
> +    ${CMAKE_CURRENT_SOURCE_DIR}/lua/?.lua
My bad, it's about regular Lua files located in this directories (misread as BINARY directory at first).

2025-03-05 17:44 UTC, ligurio commented on test/app-tap/CMakeLists.txt
> +           WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
With `WORKING_DIRECTORY` equal to `${work_dir}` test `test/app-tap/gh-2717-no-quit-sigint.test.lua` is failed with `809: LuajitError: ...G/tarantool/test/app-tap/gh-2717-no-quit-sigint.test.lua:265: time_quota is violated`.

2025-03-05 17:56 UTC, ligurio commented on test/engine-tap/lib/tester.lua
> +               os.getenv('TEST_ENGINE')
Tarantool engine is obtained via `test-run/test_run.lua` if `test_run` variable is not `nil` and when `test_run` is `nil` we use `TEST_ENGINE`. So I don't see anything bad for `test-run`. 

Also, testsuite `engine-tap` is parameterized by both engines for all tests, see:

```
[0] ~/sources/MRG/tarantool/build $ cat ../test/engine-tap/engine.cfg 
{
    "*": {
        "memtx": {"engine": "memtx"},
        "vinyl": {"engine": "vinyl"}
    }
}
```

2025-03-05 17:57 UTC, ligurio commented on test/sql-tap/lua/sqltester.lua
> +               os.getenv('TEST_ENGINE')
The same as with `engine-tap`:

Tarantool engine is obtained via `test-run/test_run.lua` if `test_run` variable is not `nil` and when `test_run` is `nil` we use `TEST_ENGINE`. So I don't see anything bad for `test-run`. 

Also, testsuite `sql-tap` is parameterized by both engines for all tests, see:

```
[0] ~/sources/MRG/tarantool/build $ cat ../test/sql-tap/engine.cfg 
{
    "*": {
        "memtx": {"engine": "memtx"},
        "vinyl": {"engine": "vinyl"}
    }
}
```

2025-03-06 10:05 UTC, Buristan commented on test/engine-tap/lib/tester.lua
> +               os.getenv('TEST_ENGINE')
Hmm, maybe it is done to be able to run this test stand-alone from the terminal (without set `TEST_ENGINE`).
I suppose it is better to add the deleted fallback case to avoid breaking this scenario of the test launch.

2025-03-06 11:36 UTC, ligurio commented on test/engine-tap/lib/tester.lua
> +               os.getenv('TEST_ENGINE')
The default value `memtx` was added by Timur Safin in 3bd870261c462416c29226414fe0a2d79aba0c74 when he introduced `engine-tap` test suite.

Added a fallback:

```diff
--- a/test/engine-tap/lib/tester.lua
+++ b/test/engine-tap/lib/tester.lua
@@ -10,8 +10,12 @@ local test = tap.test("errno")
 
 local ok, test_run = pcall(require, 'test_run')
 test_run = ok and test_run.new() or nil
-local engine = test_run ~= nil and test_run:get_cfg('engine') or
-               os.getenv('TEST_ENGINE')
+-- Default value `memtx` was added to have ability to run a
+-- `engine-tap` test w/o `test-run.py`, see commit
+-- commit 3bd870261c462416c29226414fe0a2d79aba0c74
+-- ('box, datetime: datetime comparison for indices').
+local engine = test_run and test_run:get_cfg('engine') or
+               (os.getenv('TEST_ENGINE') or 'memtx')
 
 function test.engine(self)
     return engine
```

2025-03-06 15:39 UTC, Buristan commented on test/app-tap/CMakeLists.txt
> +           WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
Nice, thanks!

2025-03-06 15:48 UTC, Buristan requested changes

2025-03-06 15:48 UTC, Buristan commented on CMakeLists.txt
I suppose it would be nice to add the following patch, since tests create tons of helper directories:

```diff
diff --git a/.gitignore b/.gitignore
index e4c77b877..8677226ee 100644
--- a/.gitignore
+++ b/.gitignore
@@ -47,6 +47,7 @@ perf/output/
 test/Makefile
 test/*/Makefile
 test/*/*/Makefile
+test/*/*-workdir-*
 Doxyfile.API
 RPM
 *.src.rpm
```

Also, we may use a single directory as a root for the tests output in each suite instead.

2025-03-06 16:40 UTC, ligurio commented on CMakeLists.txt
> I suppose it would be nice to add the following patch, since tests create tons of helper directories:

Added.

> Also, we may use a single directory as a root for the tests output in each suite instead.

I'm not sure common dir is needed for workdirs in each suite.

2025-03-07 08:43 UTC, ligurio commented on CMakeLists.txt
Finally added to the last patch and force-pushed.

```
.gitignore
CMakeLists.txt
test/CMakeLists.txt
test/app-tap/CMakeLists.txt
test/box-tap/CMakeLists.txt
test/engine-tap/CMakeLists.txt
test/engine-tap/lib/tester.lua
test/sql-tap/CMakeLists.txt
test/sql-tap/lua/sqltester.lua
```

2025-03-17 14:05 UTC, Buristan commented on CMakeLists.txt
Thanks!

2025-03-17 17:47 UTC, Buristan approved these changes
Sergey,
Thanks for the fixes!
LGTM!

2025-03-17 17:47 UTC, merged