Add field name and actual type to field type mismatch errors
tarantool/tarantool pull request #5328
Opened 2020-09-24 20:31 UTC by knazarov

An example is worth a thousand words, so:

```lua
box.cfg{}

box.schema.space.create('account', {if_not_exists=true})
box.space.account:format({ {name='id',type='unsigned'},
      {name='first_name',type='string'},
      {name='last_name',type='string'},
})

box.space.account:put({2, "John", 3})
```

This will lead to:

```
ER_FIELD_TYPE: Tuple field 3 (last_name) type does not match one required by operation: expected string, got unsigned
```

As opposed to:

```
ER_FIELD_TYPE: Tuple field 3 type does not match one required by operation: expected string
```

Which is way easier to debug, when you meet this in production.

Related to #4707

2020-09-25 11:45 UTC, sharonovd commented
Is it possible to add space name as well?

2020-09-25 12:28 UTC, knazarov commented
@sharonovd technically yes, but it requires some more source diving.

2020-10-12 20:57 UTC, Gerold103 requested changes
Generally looks fine. See 13 minor comments below.

2020-10-12 20:57 UTC, Gerold103 commented on src/box/tuple_format.c
> +
Why extra whitespace?

2020-10-12 20:57 UTC, Gerold103 commented on src/box/tuple.h
> -	if (*out > UINT32_MAX) {
Also looks like a bug - the value is silently truncated to 32 bits if `mp_decode_uint` returns something > `UINT32_MAX`.

2020-10-12 20:57 UTC, Gerold103 commented on src/box/tuple.h
> -	if (val > UINT32_MAX) {
It looks like a bug. `mp_decode_uint()` returns `uint64_t`, which was silently truncated. And still is. File an issue, or fix in the same patchset, please. Better with a test, if you want to fix it by yourself.

2020-10-12 20:57 UTC, Gerold103 commented on src/box/alter.cc
> +					 mp_type_strs[MP_STR], mp_type_strs[actual_type]);
Out of 80 symbols.

2020-10-12 20:57 UTC, Gerold103 commented on src/box/alter.cc
> +			 if (actual_type != MP_STR) {
Extra whitespace before `if` (I know it was there before, but still you can delete it since you change this line anyway).

2020-10-12 20:57 UTC, Gerold103 commented on src/box/alter.cc
> +					 mp_type_strs[MP_STR], mp_type_strs[actual_type]);
Out of 80 symbols.

2020-10-12 20:57 UTC, Gerold103 commented on src/box/alter.cc
>  			return NULL;
The tests fail on this commit. You should ensure that each of your commits passes all the tests. Also as you probably noticed, we usually specify subsystem name in the commit title. For example, `alter: `, `box: `, `raft: `, etc. In your case I could recommend just `box: `. So the title would be `box: show the actual type along with required on field type mismatch`.

2020-10-12 20:57 UTC, Gerold103 commented on src/box/tuple_format.c
> +
No need to use so many empty lines. We don't use more than 1 empty line in a row.

2020-10-12 20:57 UTC, Gerold103 commented on src/box/tuple_format.c
> +				 format->dict->names[field->token.num]);
All that can be substituted with `tt_sprintf()`.

2020-10-12 20:57 UTC, Gerold103 commented on src/box/tuple_format.c
> +		else
We never put an empty line before `else`. Please, drop.

2020-10-12 20:57 UTC, Gerold103 commented on src/box/tuple_format.c
> +			return int2str(field->token.num + TUPLE_INDEX_BASE);
If `if` has `{}`, then `else` also should have it for symmetry.

2020-10-12 20:57 UTC, Gerold103 commented on src/box/tuple_format.c
> +				       struct tuple_format* format)
Star belongs to variable name in its declaration, not to the type.

2020-10-12 20:57 UTC, Gerold103 commented on src/box/tuple_format.c
> +		if (tuple_field_ensure_child_compatibility(parent, field, format) != 0)
Out of 80 symbols.

2020-10-19 17:04 UTC, rosik commented
> Is it possible to add space name as well?

I've asked for it in #5009

2020-12-15 07:20 UTC, kyukhin commented
Detailed review was provided more than 2 months ago.

2020-12-15 07:20 UTC, closed without merging