Introduce tiny tuples
tarantool/tarantool pull request #5514
Opened 2020-11-12 17:29 UTC by PersDep

2020-12-04 07:14 UTC, alyapunov requested changes
1. The main part of the patch.
1.1. I don't like but I can live with `bool is_type` added to lots of functions. But the necessity of tracking the size of tuple manually seems to be unacceptable. See `vy_stmt_set_flags` method, it became a crap. Also I'm afraid of UB.
1.2. A least getters and setters of `bsize` should be extracted to separate commit.
2. The test
2.1. There's huge amount of bugs.
2.2. The proposed test subsystem (perf.h) is wrong and unusable.
2.3. The test itself is chaotic and hard to understand.
2.4. It does not test:
2.4.1. Performance of accessing tuple members (like bsize) in different workloads - tiny, big and mix.
2.4.2. Performance of access to indexed tuple fields. Current test of field access is inappropriate, it tests the speed of  `mp_next`.

2020-12-07 21:30 UTC, PersDep commented on cmake/compiler.cmake
> +        add_compile_flags("C;CXX" "-Wno-gnu-alignof-expression -Wno-gnu-variable-sized-type-not-at-end")
The warning is introduced by the `struct tuple` of variable size at the start of struct vy_stmt. It is now solved, struct vy_stmt is reworked.

2020-12-07 21:31 UTC, PersDep commented on src/box/vy_stmt.h
>  	struct tuple base;
Fixed.

2020-12-07 21:31 UTC, PersDep commented on src/box/vy_stmt.c
> +				!is_tiny * sizeof(uint32_t), bsize, is_tiny);
Fixed, no more extra calculations with `is_tiny`.

2020-12-07 21:31 UTC, PersDep commented on src/box/tuple.h
> +			bool is_tiny : 1;
Fixed using named structs with the same leading fields `is_tiny` which are guaranteed to be the same.

2020-12-07 21:31 UTC, PersDep commented on src/box/tuple.h
> +	uint32_t bsize[];
Well, yes, to some extent. The variable size struct should not be used as the first member of other structs. It is not anymore.
There might be some other ways to make tuples' size variable (without making `struct tuple` size variable through array of variable size at the end) but they seem to be worse. With the new fixes this one looks good enough.

2020-12-07 21:37 UTC, PersDep commented
> 1. The main part of the patch.
>    1.1. I don't like but I can live with `bool is_type` added to lots of functions. But the necessity of tracking the size of tuple manually seems to be unacceptable. See `vy_stmt_set_flags` method, it became a crap. Also I'm afraid of UB.
>    1.2. A least getters and setters of `bsize` should be extracted to separate commit.

The comments on the main part of the patch are answered. Issues are fixed in the new PR: https://github.com/tarantool/tarantool/pull/5608

> 2. The test
>    2.1. There's huge amount of bugs.
>    2.2. The proposed test subsystem (perf.h) is wrong and unusable.
>    2.3. The test itself is chaotic and hard to understand.
>    2.4. It does not test:
>    2.4.1. Performance of accessing tuple members (like bsize) in different workloads - tiny, big and mix.
>    2.4.2. Performance of access to indexed tuple fields. Current test of field access is inappropriate, it tests the speed of  `mp_next`.

Yes, as far as i see, the test should be pretty much reworked. New version will be introduced separately.

2020-12-10 04:59 UTC, PersDep commented
https://github.com/tarantool/tarantool/pull/5614

2020-12-10 11:40 UTC, PersDep commented
Continued in #5608, #5614 =

2020-12-10 11:40 UTC, closed without merging