tpch: use normal perf image instead of patched one
tarantool/tarantool pull request #5647
Opened 2020-12-21 22:00 UTC by okoshovetc

TPCH benchmark used to be launched with numerous patches applied
to tarantool's source code. Not only it does not bench actual
tarantool, it also adds extra complications in benchmarking process.
Recently we got pipeline failed only because of tpch benchmark as it
would fail to launch because it failed to apply all of the needed
patches. Instead of fixing the patches we'd better get rid of that
patching in the first place.

Fixes the [issue](https://github.com/tarantool/bench-run/issues/15)

2020-12-21 22:01 UTC, okoshovetc commented
Posmotrite kak prekrasen mir [bez narkotikov](https://gitlab.com/tarantool/tarantool/-/pipelines/232784330)

2020-12-21 23:05 UTC, tsafin requested changes
Could you please show me results including Q13, Q17 and Q20? Which are of greatest interest for us, when we are tracking SQL performance?

If current methodology disable those - we do not interested in those results.

Thanks!

2020-12-28 00:06 UTC, Totktonada commented
AFAIU, it was resolved by https://github.com/tarantool/bench-run/pull/18?

2020-12-28 12:02 UTC, tsafin commented
> AFAIU, it was resolved by [tarantool/bench-run#18](https://github.com/tarantool/bench-run/pull/18)?

Yup! (Sort of)

2020-12-28 19:57 UTC, Totktonada commented
So I guess I can close it. Feel free to reopen if I was wrong.

2020-12-28 19:57 UTC, closed without merging