Alyapunov/gh 5515 some mvcc crash
tarantool/tarantool pull request #6194
Opened 2021-07-02 14:27 UTC by alyapunov

Subj

2021-07-05 15:21 UTC, Korablev77 commented on test/box/tx_man.test.lua
> +s:drop()
Test executes fine on master branch

2021-07-05 15:22 UTC, Korablev77 requested changes
CI is red; there are also conflicts with master branch...

2021-07-07 14:56 UTC, Korablev77 commented
These patches also fix https://github.com/tarantool/tarantool/issues/6137

2021-07-08 11:27 UTC, alyapunov commented on test/box/tx_man.test.lua
> +s:drop()
True. added 100% test

2021-07-08 12:28 UTC, alyapunov commented
> CI is red; there are also conflicts with master branch...

fixed

2021-07-09 10:56 UTC, Korablev77 approved these changes
LGTM

2021-07-09 10:56 UTC, merged

2021-07-09 11:27 UTC, Korablev77 commented
Pushed also to 2.8 and 2.7