Added casting int to double for operations with field double in space
tarantool/tarantool pull request #6302
Opened 2021-08-09 11:11 UTC by wey1and

2021-08-09 11:24 UTC, tsafin requested changes
Also, it would be a good idea to put non-empty commit message and pull-request description.

2021-08-09 11:24 UTC, tsafin commented on src/box/field_def.c
> +	/* [FIELD_TYPE_DOUBLE]   =  */ (1U << MP_DOUBLE) | (1U << MP_UINT) | (1U << MP_INT),
I do understand that that was my patch suggested, but, in any case, I've discovered that during later discussions.

I believe, that in this line we should also allow `MP_FLOAT` data types. 

P.S.
I don't know yet how to generate `MP_FLOAT` messagepack data from generic Tarantool tuple.

2021-08-09 11:24 UTC, tsafin commented on test/engine/double.test.lua
> +box.space.space_with_double:insert { 1, 1 }
I'd use `1.0` also. (It's the same `1` though once kept to Lua number, but regardless)

2021-08-11 12:07 UTC, wey1and commented
Full implementation requires many unacceptable changes.

2021-08-11 12:07 UTC, closed without merging