lua: fix several possibility crashes in lua triggers implementation.
tarantool/tarantool pull request #6312
Opened 2021-08-12 13:50 UTC by EvgenyMekhanik

There are two cases in lua trigger implementation, which leads
to access to freed memory: if trigger removes itself and if
trigger yields and someone destroy it. These problems was fixed
by remembering the necessary fields from the trigger structure
in local variables before calling trigger function.

Closes #6266

2021-08-13 15:40 UTC, Korablev77 approved these changes
LGTM (except I'm not sure that we have lua/triggers subsystem).

2021-08-16 10:43 UTC, locker requested changes

2021-08-16 10:43 UTC, locker commented on changelogs/unreleased/gh-6266-fix-crash-in-lua-triggers.md
> +  when it's yield.
Please add to the changelog: (gh-6266)

2021-08-16 10:43 UTC, locker commented on src/lua/trigger.c
> +	lbox_push_event_f push_event = trigger->push_event;
You don't need to store push_event in a local variable - there's no yields before it is called.

2021-08-16 10:43 UTC, locker commented on src/lua/trigger.c
> +	lbox_pop_event_f pop_event = trigger->pop_event;
Let's make this more clear:

1. Move this right before the point where the trigger might get destroyed, i.e. before luaT_call.
2. Add a comment explaining why you need to do this.
3. Set trigger to NULL afterwards to emphasize that it isn't safe to use it anymore.

```C
int nargs = 0;
if (trigger->push_event != NULL) {
        nargs = trigger->push_event(L, event);
}
/* explain why */
lbox_pop_event_f pop_event = trigger->pop_event;
trigger = NULL;
if (luaT_call(L, nargs, LUA_MULTRET)) {
```

2021-08-16 14:02 UTC, locker approved these changes

2021-08-17 07:22 UTC, VitaliyaIoffe approved these changes
QA LGTM

2021-08-18 12:39 UTC, merged