Add worker_dispatch of commit hash to all existing workflows
tarantool/tarantool pull request #6317
Opened 2021-08-13 10:34 UTC by drakonhg

Git checkout was added to workflows where packaging is located
to check if workflow_dispatch is working correctly or not

There is three types of testing
  - Short commit hash
  - Long commit hash
  - Without hash

2021-08-15 13:52 UTC, VitaliyaIoffe commented
Seems good!
![image](https://user-images.githubusercontent.com/34002333/129480813-751620f8-8bfc-4b32-b04a-de7943999fd3.png)

2021-08-15 13:58 UTC, VitaliyaIoffe commented
Please, fix the commit message. 

Firstly, you wrote about testing formats. That's good info, but it is not enough. Write about why this change is useful. 
Secondly, your commit title `Add worker_dispatch of commit hash to all existing workflows` has length reater than 72 characters. 72 characters is a recommended length for a title. Also, it's good to start title from 'github-ci: <explanation>'. 
Maybe something like this:
`github-ci: provide commit hash as a manual trigger`
What do you think?

2021-08-16 06:56 UTC, VitaliyaIoffe commented
https://github.com/tarantool/tarantool/runs/3320415906?check_suite_focus=true

2021-08-16 07:04 UTC, drakonhg commented
> Please, fix the commit message.
> 
> Firstly, you wrote about testing formats. That's good info, but it is not enough. Write about why this change is useful. Write what would be done after you put full hash, small hash, wrong hash and no hash.
> Secondly, your commit title `Add worker_dispatch of commit hash to all existing workflows` has a length greater than 50 characters. 50 characters is a recommended length for a title. Also, it's good to start title from 'github-ci: '.
> Maybe something like this:
> `github-ci: provide commit id within manual trigger`
> What do you think?

Sounds great. Will do

2021-08-23 07:55 UTC, VitaliyaIoffe requested changes
Tarantool involves a few submodules. If we checkout input a commit only the tarantool repo and packaging it, it would be inconsistent, cause we haven't updated submodules. 
So, after checkout we should fetch all submodules.

2021-08-23 11:35 UTC, VitaliyaIoffe commented on .github/workflows/ubuntu_20_04.yml
> -          submodules: recursive
return please

2021-08-23 11:51 UTC, VitaliyaIoffe requested changes
Also, this issue is about packaging. Please, left the change only in workflows, where there is packaging step.

2021-08-23 13:38 UTC, VitaliyaIoffe requested changes

2021-08-23 13:38 UTC, VitaliyaIoffe commented on .github/workflows/source.yml
> +          git checkout ${{ github.event.inputs.commit }}
delete please this step everywhere.

2021-08-23 13:38 UTC, VitaliyaIoffe commented on .github/workflows/source.yml
> +        required: false
The issue is about packaging, please delete this change from workflows without packaging or make this change same on all workflows.

2021-08-23 14:46 UTC, VitaliyaIoffe requested changes

2021-08-23 14:46 UTC, VitaliyaIoffe commented on .github/workflows/ubuntu_21_04.yml
> +        required: true
why is here `true`?

2021-08-23 14:46 UTC, VitaliyaIoffe commented on .github/workflows/fedora_33.yml
> +
blank line

2021-08-30 07:39 UTC, VitaliyaIoffe approved these changes
LGTM

2021-08-31 18:18 UTC, VitaliyaIoffe commented
@igormunkin, do we need to upload packages anywhere?

2021-09-01 11:17 UTC, VitaliyaIoffe requested changes
Should upload packages to artifacts

2022-02-23 22:07 UTC, Totktonada commented
It is stalled for several months, so unlikely will receive updates. I'll close this pull request. It is linked to the issue, so the effort will not gone. Someone, who will continue the work, can reuse it.

Feel free to reopen if it is a mistake.

2022-02-23 22:07 UTC, closed without merging