github-ci:Create new Telegram Notifier action
tarantool/tarantool pull request #6373
Opened 2021-08-20 15:26 UTC by drakonhg

The problem was that previous action worked 50/50 or
did not work at all. So I decided to create a new action
which is functional and has the same process logic

Also two additional actions were added. They are required
for telegram action work better. First one is setting
additional environment variables that we are need for
message to be correctly structured and another is to check
if commit sha exist or not

All explanations can be found in README.md of each action

2021-08-30 07:55 UTC, VitaliyaIoffe requested changes
Please, rebase on the master

2021-08-30 07:55 UTC, VitaliyaIoffe commented on .github/actions/telegram-notifier/Dockerfile
> +# Container image that runs your code
Why do we need Dockerfile?

2021-08-30 07:55 UTC, VitaliyaIoffe commented on .github/actions/telegram-notifier/script.py
> +def check_branch_name(branch_name):
docstring, please

2021-08-30 07:55 UTC, VitaliyaIoffe commented on .github/actions/telegram-notifier/script.py
> +def send_message(chat_id, message,
docstring, please

2021-08-30 07:55 UTC, VitaliyaIoffe commented on .github/actions/telegram-notifier/script.py
> +        ]
You used different alignments in the file.
I think is more preferable: 
```
some = [
    foo, 
    bar
]
```

2021-08-30 07:55 UTC, VitaliyaIoffe commented on .github/actions/telegram-notifier/script.py
> +
`E302 expected 2 blank lines, found 1`

2021-08-30 07:55 UTC, VitaliyaIoffe commented on .github/actions/telegram-notifier/script.py
> +    edit_message = message.replace('-', '\\-').replace('_', '\\_').replace('.', '\\.')
Firstly, these replacements are not obvious.
Secondly, `E501 line too long (86 > 79 characters)`

2021-08-30 07:55 UTC, VitaliyaIoffe commented on .github/actions/telegram-notifier/script.py
> +    print(response.json())
Do we need this print?

2021-08-30 07:55 UTC, VitaliyaIoffe commented on .github/actions/telegram-notifier/script.py
> +    print(response.json())
Why have not we checked the response code?

2021-08-30 07:55 UTC, VitaliyaIoffe commented on .github/actions/telegram-notifier/action.yml
> +  image: 'Dockerfile' # we will use our own Dockerfile to build an image and run it.
no newline at end of file

2021-08-30 07:55 UTC, VitaliyaIoffe commented on .github/actions/configure_github_envs/action.yml
> +      shell: bash
`no newline at end of file`

2021-08-30 07:55 UTC, VitaliyaIoffe commented on .github/actions/commit-hash-check/action.yml
> +      shell: bash
`no newline at end of file`

2022-02-24 08:41 UTC, kyukhin commented
I guess we should move to another messenger. Closing.

2022-02-24 08:41 UTC, closed without merging