Libev update to version 4.33
tarantool/tarantool pull request #6404
Opened 2021-08-31 16:28 UTC by EvgenyMekhanik

Besides updating libev this patch fixed error in implementation
of `ev_io_closing`: this function is called to do same work as
`fd_kill` and should call it after checking fd (in `coio_close`
we pass invalid event value, that leads to assertion in new libev
version).

Closes #4909

2021-09-15 08:58 UTC, Korablev77 requested changes
I see that in the libev trunk there's no ev_io_closing() function at all:
http://cvs.schmorp.de/libev/ev.c?view=markup#l4386

I suggest to remove it as well to keep our libev in consistent state with original repo. Otherwise we will have to resolve conflicts next time during libev update.

2021-09-15 12:10 UTC, EvgenyMekhanik commented
> I see that in the libev trunk there's no ev_io_closing() function at all:
> http://cvs.schmorp.de/libev/ev.c?view=markup#l4386
> 
> I suggest to remove it as well to keep our libev in consistent state with original repo. Otherwise we will have to resolve conflicts next time during libev update.

We need this function, because we need a way to remove invalid fd from libev internals. 'fd_kill' is internal libev function and also it does not check fd.

2021-09-16 12:58 UTC, locker approved these changes

2021-10-04 09:38 UTC, Korablev77 approved these changes

2021-10-05 10:05 UTC, merged