memtx: raise an error if argument of select() is a "clear" dict
tarantool/tarantool pull request #6457
Opened 2021-09-23 12:27 UTC by drewdzzz

Currently, select/pairs/get look at an :array part of passed table,
that is why different problems occurs when passed to select() table
is not a regular array.

Now we will check if passed table is not "clear dict"
(not empty table without array part). Invalid queries
like s:select{key = 'value'} will fail with an appropriate
error, but the problems with dicts containing array part
still remain (for example, s:select{1, key = 'value'} is
the same as s:select{1}).

Closes #6167

2021-09-23 14:12 UTC, locker requested changes

2021-09-23 14:12 UTC, locker commented on src/box/lua/schema.lua
> +    end
AFAIU you don't need this, because tuple_encode never returns nil - it raises an exception on error.

2021-09-24 07:57 UTC, locker commented on src/box/lua/schema.lua
> +    end
@drewdzzz Please reply to the comment after addressing it so that reviewers can see what changed. Something like "Fixed" is good enough.

2021-09-24 07:58 UTC, locker approved these changes

2021-09-24 07:58 UTC, locker commented on src/box/lua/tuple.lua
> +            return box.error(box.error.TUPLE_NOT_ARRAY)  -- dictionary cannot represent a tuple
The line is too long - should be < 80 characters. Please fix. Other than that looks good.

2021-09-29 13:35 UTC, Korablev77 commented
Changelog is missing. Otherwise LGTM

2021-09-29 16:19 UTC, Korablev77 reviewed
Extension of changelog file should be .md :)

2021-12-10 15:54 UTC, merged