github-ci: add ubuntu groovy (20.10) workflow
tarantool/tarantool pull request #6736
Opened 2021-12-23 07:55 UTC by kyukhin

Add ubuntu-impish workflow, which runs on push and pull-requests.

Closes #6566

2021-12-30 16:02 UTC, artembo requested changes

2021-12-30 17:31 UTC, artembo approved these changes

2022-01-10 14:20 UTC, ylobankov approved these changes
LGTM

2022-01-12 08:09 UTC, NickVolynkin commented
Сначала залить патч от Ярослава

2022-01-12 08:25 UTC, merged