sp/gh 6706 relay heartbeat
tarantool/tarantool pull request #6769
Opened 2021-12-31 09:53 UTC by sergepetrenko

- relay: remove unused row_count parameter
- relay: send heartbeats while reading a WAL

2022-01-19 22:39 UTC, Gerold103 approved these changes
Clean and working, thanks!

2022-01-20 21:40 UTC, sergos requested changes
The commit message is not looking good in part you mention previous commits: in git it is longer than needed, while PR shortened them so that formatting is garbled too. You can keep just 7 symbols of the commit hash in the message, so they will match.

Also, there's no test on the fact the problem is addressed and I see no ERRINJ for the reading the WAL, only for writing it. Could be a good starting point for a 'too log WAL read', since we may have more problems caused by the file system availability.

2022-02-02 13:55 UTC, sergos approved these changes

2022-02-07 09:13 UTC, kyukhin approved these changes

2022-02-07 09:13 UTC, merged