Spelling errors in module.h
tarantool/tarantool pull request #6943
Opened 2022-03-19 15:50 UTC by chakkk309

scenarious is changed to scenarios in `src/box/lua/tuple.h`
Arrat is changed to Array in `src/box/box.h`
Retrive is changed to Retrieve、interator is changed to iterator in `src/box/index.h`
byffer is changed to buffer、zerod-based is changed to zero-based、Interator is changed to iterator in  `src/box/tuple.h`
timeoout  is changed to timeout in `src/lib/core/coio.h`
convertable  is changed to  convertible in `src/lua/utils.h`
macroses is changed to macros、strucrs is changed to structs、indepedent is changed to independent in `src/trivia/util.h`
othrewise is changed to otherwise、hadler is changed to handler in `src/on_shutdown.h`

2022-03-22 10:28 UTC, kyukhin commented
Hello!
Please fix linter issues.

2022-03-22 11:31 UTC, drewdzzz requested changes

2022-03-24 05:05 UTC, NickVolynkin commented
The linter issues that Kirill is talking about are in the `checkpatch` workflow: https://github.com/tarantool/tarantool/runs/5630903691?check_suite_focus=true

2022-03-24 16:14 UTC, chakkk309 commented on src/lua/utils.h
> + * Like lua_call(), but with the proper support of Tarantool errors.
Thank you, I have squashed this commit.

2022-03-24 17:24 UTC, drewdzzz requested changes
Well done! You are about closing the issue, but there are a couple of things left to fix:

Firstly, you haven't fix only one typo:
> **Absense** of trailing key parts fails the check.

It is placed in the description of `box_key_def_validate_full_key` function.

Secondly, write `Closes #<issue number>` in your commit description to close the corresponding issue.

Thirdly, I think that `docs: fix typos in module.h` would be a better commit message :)

And the last one, you need to [deal with checkpatch](https://github.com/tarantool/tarantool/runs/5630903691?check_suite_focus=true). Your commit does not require test, doc request or changelog and you must write it to the commit description. Just like at the end of this one - https://github.com/tarantool/tarantool/commit/63de77fd8119fd7f166ed2b70af083202db95263. You can use reasons like `no behavior changes` or `fix typos`.

2022-03-25 12:07 UTC, drewdzzz approved these changes
Thank you for the patch, LGTM!

2022-03-25 12:48 UTC, alyapunov approved these changes

2022-03-25 12:51 UTC, alyapunov approved these changes

2022-03-29 10:59 UTC, merged