mvcc: track nothing-found range read
tarantool/tarantool pull request #7055
Opened 2022-04-21 08:24 UTC by alyapunov

MVCC must track a read set of transaction, including cases when
the select returns an empty result. In this case MVCC has two
options: to store a point key if the select has a full key or
to store a gap otherwise.

By a mistake the second variant was not implemented. Fix it now.

Closes #7025

2022-04-21 11:30 UTC, drewdzzz requested changes

2022-04-21 11:30 UTC, drewdzzz commented on test/box-luatest/gh_7025_mvcc_dirty_range_test.lua
> +g.test_empty_range_select_left = function()
Please, use different names for different tests: now only one of the three tests will run.

2022-04-21 11:30 UTC, drewdzzz commented on src/box/memtx_tree.cc
> +		memtx_tx_track_gap(in_txn(), space, idx, successor, type,
Nit: you can use variable `txn` instead of `in_txn()` for code uniformity.

2022-04-21 11:30 UTC, drewdzzz commented on test/box-luatest/gh_7025_mvcc_dirty_range_test.lua
> +        t.assert_equals(s:select{}, {{1, 0}, {2, 0}, {3, 0}})
Nit: the same code is encountered three times. Maybe it's better to write one test with loop?

2022-04-22 11:23 UTC, CuriousGeorgiy commented on test/box-luatest/gh_7025_mvcc_dirty_range_test.lua
> +        if box.space.test then
Nit: doesn't `box.space.test` always exist?

2022-04-22 11:31 UTC, CuriousGeorgiy commented on src/box/memtx_tree.cc
> +				   it->key_data.key, it->key_data.part_count);
I don't like this logic duplication:
https://github.com/tarantool/tarantool/blob/a9e30fb365c1643484054aa07038c015383e7faa/src/box/memtx_tree.cc#L706-L715

2022-04-22 11:38 UTC, CuriousGeorgiy commented on test/box-luatest/gh_7025_mvcc_dirty_range_test.lua
> +        local strkey = tostring(key)
Nit: AFAIK, this conversion is done automatically by the Lua runtime.

2022-04-25 07:11 UTC, merged