lua: fix luacheck warnings in src/box/console.lua
tarantool/tarantool pull request #7261
Opened 2022-06-10 14:24 UTC by Lord-KA

Closes #5032

2022-06-10 16:10 UTC, ligurio commented
@Lord-KA why you haven't run full ci before requesting code review?

2022-06-12 14:51 UTC, Lord-KA commented
My bad, fixed.

2022-06-14 09:34 UTC, ligurio requested changes
Gleb, thanks for the patch.
I have some thoughts regarding changes. In fact, changes required for ticket are trivial and there are a number of ways how to do it. Some ways we already discussed verbally.
I'm a bit confused by the method you have chosen to fix - say that variable is used, however it is not used at all in a function's body.
Let me remind the main idea - we need to fix warnings produced by luacheck and don't make code less readable.

2022-06-15 12:46 UTC, ligurio approved these changes
Well, let's  suppress it inline.

LGTM

2022-06-16 10:16 UTC, Buristan reviewed
As for me it is more clear to anonymize a variable that isn't used. I don't need to reread function body several times to be sure that this variable is unused. If I want to see what is this unnamed variable, I'll see the function's usage (I already need to do it to understand what is this mystical `storage` or `func` is).

Also, there is no understanding at start what the variable is really unused for functions with more than 2 arguments like `set_param()`.

Moreover, for functions like `help_wrapper()` and `quite()` we have no need to declare this unused argument at all -- just use declaration without arguments. And for `client_handler()` function, we can just omit the last unused `peer` argument.

But this is matter of taste, so feel free to ignore.

2022-06-16 11:03 UTC, Totktonada commented
Raw idea: add something like C's `(void)` cast to mark function arguments as unused. Say, introduce the `unused()` function (no-op). Will it work?

2022-06-21 10:39 UTC, Lord-KA commented
Once again, I don't think that missing an unused var warning is a big deal. Turning suppression off requires just slightly modifying its comment, you don't have to check for unused vars manually. But generally, I think as you said, the best way to handle it is with a `_` prefix. maybe we can configure it in our `.luacheckrc`?

2022-06-21 11:56 UTC, Lord-KA commented
Do I need a doc request for this change?

2022-06-21 15:01 UTC, Buristan approved these changes
Hi, thanks for the fixes!
LGTM, except a single nit below.

Also, you may mention in the commit message that this allows declaration of function (handlers) with an expected standardized interface.

2022-06-21 16:06 UTC, Lord-KA commented on .luacheckrc
> +    "212/_.*",
Thx, missed that.

2022-06-21 16:08 UTC, Lord-KA commented
> Hi, thanks for the fixes! LGTM, except a single nit below.
> 
> Also, you may mention in the commit message that this allows declaration of function (handlers) with an expected standardized interface.

Fixed.

2022-08-04 14:11 UTC, merged

2022-08-04 14:16 UTC, igormunkin commented
Also backported to 2.10 in scope of b076f7b (2.10.0-183-gb076f7b71).