Get rid of fiber_set_cancellable in txn_limbo and raft
tarantool/tarantool pull request #7281
Opened 2022-06-17 21:33 UTC by Gumix

See commit messages.

Part of #7166

2022-06-21 22:36 UTC, Gerold103 requested changes
Thanks for the patch!

2022-06-22 12:07 UTC, Gumix commented on src/box/txn_limbo.c
> +		rc = fiber_cond_wait_deadline(&limbo->wait_cond, deadline);
Done

2022-06-23 21:59 UTC, Gerold103 approved these changes
Thanks for the fixes!

2022-06-24 08:31 UTC, locker approved these changes

2022-06-24 08:31 UTC, merged