ci: fix conditions in publishing workflow
tarantool/tarantool pull request #7557
Opened 2022-08-10 12:38 UTC by ligurio

NO_CHANGELOG=ci
NO_DOC=ci
NO_TEST=ci

2022-08-10 12:43 UTC, ylobankov commented on .github/workflows/publish-module-api-doc.yaml
> +    # Run on push to the 'master' or on pull request if the 'full-ci' label is
Could you please add `branch` after `'master'`?

2022-08-10 15:30 UTC, ylobankov commented on .github/workflows/publish-module-api-doc.yaml
> +    # Run on push to the 'master' or on pull request if the 'full-ci' label is
Looks like fixed.

2022-08-10 15:30 UTC, ylobankov commented
Please resolve conflicts.

2022-08-11 10:48 UTC, igormunkin approved these changes
@ligurio, thanks for the patch! LGTM, as trivial.

2022-08-11 10:55 UTC, igormunkin requested changes
@ligurio, thanks for the patch! Please mention the previous commit and the fixup as the reason the condition of the workflow is changed. Also, describe the changes a little in the commit message. Finally, rebase your changes on the bleeding master to resolve the conficts.

By the way, what about the concurrency section used in all other workflows? @ylobankov, do we need it here too?

2022-08-12 11:09 UTC, ylobankov commented
> @ligurio, thanks for the patch! Please mention the previous commit and the fixup as the reason the condition of the workflow is changed. Also, describe the changes a little in the commit message. Finally, rebase your changes on the bleeding master to resolve the conficts.
> 
> By the way, what about the concurrency section used in all other workflows? @ylobankov, do we need it here too?

This workflow is not so heavy, but we can add it for consistency with others.

2022-08-17 15:28 UTC, ylobankov approved these changes
LGTM, please fix Igor's comments.

2022-08-24 10:47 UTC, igormunkin approved these changes
@ligurio, thanks for the fixes! LGTM.

2022-08-24 10:49 UTC, merged