ci: improve `report-job-status` README
tarantool/tarantool pull request #7565
Opened 2022-08-11 17:55 UTC by lastoCHka42

This patch add instruction how to use `report-job-status` from
forks.

NO_DOC=ci
NO_TEST=ci
NO_CHANGELOG=ci

2022-08-15 22:43 UTC, ylobankov requested changes

2022-08-16 14:27 UTC, lastoCHka42 commented on .github/actions/report-job-status/README.md
> +If you want to use this action from fork, add the following information to your
Fixed

2022-08-16 15:14 UTC, NickVolynkin commented on .github/actions/report-job-status/README.md
> +This action won't work from pull request, because GitHub secrets are not
in pull requests

2022-08-16 15:14 UTC, NickVolynkin commented on .github/actions/report-job-status/README.md
> +available for pull requests from fork (neither repository secrets nor personal
in pull requests opened from forks

2022-08-16 15:14 UTC, NickVolynkin commented on .github/actions/report-job-status/README.md
> +creating/updating a or any event in other branches.
What is "a"?

2022-08-17 07:48 UTC, lastoCHka42 commented on .github/actions/report-job-status/README.md
> +creating/updating a or any event in other branches.
fixed

2022-08-17 07:48 UTC, lastoCHka42 commented on .github/actions/report-job-status/README.md
> +available for pull requests from fork (neither repository secrets nor personal
done

2022-08-17 07:48 UTC, lastoCHka42 commented on .github/actions/report-job-status/README.md
> +This action won't work from pull request, because GitHub secrets are not
done

2022-08-18 08:08 UTC, lastoCHka42 commented on .github/actions/report-job-status/README.md
> +creating/updating any event in other branches.
done

2022-08-18 12:06 UTC, lastoCHka42 commented on .github/actions/report-job-status/README.md
> +This action won't work in pull request, because GitHub secrets are not
done

2022-08-18 14:39 UTC, ylobankov commented on .github/actions/report-job-status/README.md
> +creating/updating pull request or any event in other branches.
Please revert `a`.

2022-08-18 14:40 UTC, ylobankov reviewed
Please update PR and commit message description according to your changes.

2022-08-19 08:25 UTC, lastoCHka42 commented on .github/actions/report-job-status/README.md
> +creating/updating pull request or any event in other branches.
done

2022-08-22 10:32 UTC, NickVolynkin approved these changes

2022-08-22 12:25 UTC, ylobankov approved these changes

2022-08-22 12:26 UTC, merged