Add build RedOS linux package
tarantool/tarantool pull request #7606
Opened 2022-08-25 12:53 UTC by foxzi

Create workflow building RedOS linux rpm and publish it to official repo.
Package creates by https://github.com/packpack/packpack.

2022-08-26 10:49 UTC, ylobankov requested changes
Please add a changelog entry with this commit like it is done here https://github.com/tarantool/tarantool/commit/fccb6bc0870451152937ddf535a953877fe1fe68.

2022-08-26 10:49 UTC, ylobankov commented on .github/workflows/redos_7_3.yaml
> +      - 'foxzi-build-redos-rpm'
Please delete this branch.

2022-08-29 09:51 UTC, foxzi commented on .github/workflows/redos_7_3.yaml
> +      - 'foxzi-build-redos-rpm'
done

2022-08-30 17:49 UTC, ylobankov requested changes
Please add a changelog entry with this commit like it is done here https://github.com/tarantool/tarantool/commit/fccb6bc0870451152937ddf535a953877fe1fe68.

2022-08-31 12:38 UTC, foxzi commented
> 

done

2022-08-31 19:01 UTC, ylobankov reviewed
The patch looks almost good. Could you please rewrite the commit message to something like this?

```
ci: add RedOS 7.3 rpm package build (x86_64)

Add the redos_7.3.yml workflow to build Tarantool packages (x86_64) for
the RedOS 7.3 system.

Packages are created by https://github.com/packpack/packpack.
```

2022-09-01 09:32 UTC, foxzi commented
> The patch looks almost good. Could you please rewrite the commit message to something like this?
> 
> ```
> ci: add RedOS 7.3 rpm package build (x86_64)
> 
> Add the redos_7.3.yml workflow to build Tarantool packages (x86_64) for
> the RedOS 7.3 system.
> 
> Packages are created by https://github.com/packpack/packpack.
> ```

ok

2022-09-06 13:22 UTC, merged

2022-09-06 13:30 UTC, ylobankov commented
Cherry picked to 2.10.