test: fix another readline dependent test
tarantool/tarantool pull request #7621
Opened 2022-08-29 07:33 UTC by nshy

The test fails on dev installation if it's readline configuration
(.inputrc) changes prompt. Use default readline configuration for
a test.

Closes #7620

NO_DOC=test changes
NO_TEST=test changes
NO_CHANGELOG=test changes

2022-08-31 08:57 UTC, Lord-KA approved these changes
I could not find a better way to set Readline configuration to default, so this seems fine, except for the comment above. LGTM after fixing it.

2022-08-31 08:57 UTC, Lord-KA commented on test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua
> +    local cmd = [[printf '42\n' | ]] .. 'INPUTRC=Pheiphe2 ' ..
I agree with Sergey, this way you can shorten comment and save readability. The "other places" are all in [gh-2717-no-quit-sigint.test.lua](https://github.com/tarantool/tarantool/pull/7621/commits/976b3bc22a59f649d17864713c32e4bac9b99ed2#diff-321025ff9a1bd62f89bdefd09fe95897dbdb3cc6cf258625440120004d409a74) and don't have explicit comments about the meaning of the string. One could confuse them with a weird readline configuration name.

2022-08-31 09:02 UTC, Totktonada commented on test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua
> +    local cmd = [[printf '42\n' | ]] .. 'INPUTRC=Pheiphe2 ' ..
We recently looked at the relevant tests with @tsafin and initially we both were confused by this string. So +2 here.

2022-08-31 09:08 UTC, nshy commented on test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua
> +    local cmd = [[printf '42\n' | ]] .. 'INPUTRC=Pheiphe2 ' ..
ok

2022-08-31 09:17 UTC, Lord-KA commented on test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua
> +    local cmd = [[printf '42\n' | ]] .. 'INPUTRC=Pheiphe2 ' ..
The alternative to `non_existent_inputrc` could be `/dev/null`.

2022-09-02 11:34 UTC, nshy commented
Centos 7 still fails if we remove that gsub deleting \e[?1034h escape sequence. So looks like it is compiled in. By the way `gh-2717-no-quit-sigint.test.lua` that makes similar tests just disabled.

I'll return gsub back.

2022-09-05 07:44 UTC, Lord-KA approved these changes
Thanks for the patch, LGTM.

2022-09-05 14:30 UTC, locker requested changes

2022-09-05 14:30 UTC, locker commented on test/app-tap/gh-2717-no-quit-sigint.test.lua
> -local cmd = 'INPUTRC=Pheiphe2 ' .. TARANTOOL_PATH .. ' -i 2>&1'
Why is `Pheiphe2` any better than `non_existent_file`? Why isn't another test updated? IMO better create a real inputrc file for tests.

Anyway, the two patches should be squashed.

2022-09-05 14:39 UTC, locker commented on test/app-tap/gh-2717-no-quit-sigint.test.lua
> -local cmd = 'INPUTRC=Pheiphe2 ' .. TARANTOOL_PATH .. ' -i 2>&1'
Sorry - thought you replaced `non_existent_file` with `Pheiphei2`. Never mind - everything's fine. Still, I wouldn't split patches in such a fine grained way - "While we are at it, fix the non existent file name" in the commit message would do just fine.

2022-09-05 14:39 UTC, locker approved these changes

2022-09-05 14:39 UTC, merged