luajit: proxy -j and -b flags
tarantool/tarantool pull request #7855
Opened 2022-10-27 14:21 UTC by fckxorg

There are two flags in the LuaJIT useful for debugging and runtime configuration purposes: `-j` and `-b`. However, if you want to check the same Lua code from the Tarantool, you will need to make some adjustments in the script itself, as those flags are not present in the Tarantool's CLI.

This patch introduces those flags to the Tarantool, so debugging is much more convenient now. Flags are working the same as they do in the LuaJIT.

Closes #5541

2022-10-27 14:35 UTC, Totktonada commented on src/main.cc
> -		case 'v':
Please, don't do that. The semantic is the same as for the if-elseif-else chain and it should be indented similarly. There is no logical double nesting despite lexical double nesting. A code should represent a logic behind it, so the logic wins here.

2022-11-09 00:28 UTC, Totktonada commented on test/box-py/args.test.py
> +server.test_option("-j on -e ''")
The checkpatch warning is about a trailing whitespace:

```diff
ERROR:TRAILING_NEWLINE: trailing newline
#444: FILE: test/box-py/args.result:182:
+tarantool -j on -e 
+
```

At least you can do something like the following:

```python
cmd = <...>
res = server.test_option_get(cmd, silent=True)
print(cmd)
print(res)
```

It uses [test_option_get](https://github.com/tarantool/test-run/blob/07a0c00c8b54e1e4bc2a458ce7e76b5cd790eefb/lib/tarantool_server.py#L1198) from test-run.

I would rewrite the test to luatest and drop `test_option` and `test_option_get` from test-run, but not necessarily in this patchset.

2023-01-09 08:43 UTC, tsafin requested changes

2023-01-09 08:43 UTC, tsafin commented on src/main.cc
> +		case 'b':
There is one case left unhandled - when there was `-b` option without modifiers, and output file provided. Patched tarantool rejects this case, while original luajit does handle it correctly:

```
✘-1 ~/tarantool/build [tsafin/luajit-hack-0 L|…17⚑ 8]
11:37 $ ./src/tarantool -b ../debug-getsources-0.lua debug-getsources.out
Save LuaJIT bytecode: luajit -b[options] input output
  -l        Only list bytecode.
  -s        Strip debug info (default).
  -g        Keep debug info.
  -n name   Set module name (default: auto-detect from input name).
  -t type   Set output file type (default: auto-detect from output name).
  -a arch   Override architecture for object files (default: native).
  -o os     Override OS for object files (default: native).
  -e chunk  Use chunk string as input.
  --        Stop handling options.
  -         Use stdin as input and/or stdout as output.

File types: c h obj o raw (default)
✔ ~/tarantool/build [tsafin/luajit-hack-0 L|…17⚑ 8]
11:38 $ luajit -b ../debug-getsources-0.lua debug-getsources.out
```

2023-01-09 08:43 UTC, tsafin commented on src/main.cc
> +		case 'b':
Also, we better modify the reported message to include tarantool name instead of luajit.

2023-01-18 15:46 UTC, tsafin commented on src/main.cc
> +		case 'b':
Also I'd like to highlight, that I want this patch landed to master before #7929 where I modify all the same `init.c` for introduction of `-d` option, and given `-b` and `-j` changes from this pull request the possible resultant code with `-d` added similarly would look more generic (and shorter).

2023-02-01 21:41 UTC, tsafin approved these changes
Thanks, it's now handling a full set of possible `-b` options (including arg-less). Also, this patch is now part of debugger option code #7929 (I've rebased my PR upon the current one).

2023-02-17 19:01 UTC, igormunkin commented
Superseded by #8334. Closing.

2023-02-17 19:01 UTC, closed without merging