raft: fix box.ctl.promote() hanging when cannot gather a quorum
tarantool/tarantool pull request #8221
Opened 2023-01-26 12:52 UTC by sergepetrenko

Fixing a bug with nodes in 'manual' election mode bumping the term excessively revealed a hang in election_pre_vote test. Turns out the test passed thanks to the previous buggy behaviour.

The following behaviour is expected: when a node is configured in manual election mode, calling box.ctl.promote() on it should make it bump term once, try to gather votes and fail on timeout.

Once the extra term bump on timeout was removed in commit 5765fdc4e4ec ("raft: fix 'manual' nodes bumping the term excessively"), box.ctl.promote() without a quorum started hanging.

Let's return the correct behaviour: 'manual' nodes should transition back to follower if an election timeout passes after the promotion without any term outcome.

Enable the test_promote_no_quorum testcase of election_pre_vote test back, since it's fixed now.

Follow-up #8168
Closes #8217

NO_DOC=bugfix
NO_CHANGELOG=changes not released behaviour

2023-01-26 17:45 UTC, grafin requested changes
Thanks for the patch! Only one comment from me, about timingout conditions, please take a look.

2023-01-27 08:14 UTC, sergepetrenko commented on test/replication-luatest/gh_8168_extra_term_bump_test.lua
> +    t.tarantool.skip_if_not_debug()
Yeah, it's a nice one.
There's also `t.skip('reason')` which's useful when need to disable only part of the test cases, not the whole test (for example https://github.com/tarantool/tarantool/commit/3273a51d7798a86fcfc41c04ce0d67377a478311).

2023-01-27 08:56 UTC, sergepetrenko commented on src/box/raft.c
> +		if (box_election_mode == ELECTION_MODE_MANUAL) {
It seems to me this condition is hit only when we timeout:
First of all, the yielding loop is only exited when either the fiber is cancelled or `ctx.is_done` is set.
Fiber cancellation is handled first, and we are left with various reasons for `ctx.is_done` to be set:
1. Term increased
2. Same term, but not is_candidate anymore (reconfigured to voter or 'manual' node timed out, or probably candidate fenced?)
3. Leader found in this term (including self).

Term increase and leader found are handled (although in a strange order, it seems).

2023-01-30 22:03 UTC, Gerold103 requested changes
Thanks for the patch!

2023-02-01 07:48 UTC, sergepetrenko commented on src/lib/raft/raft.c
> +	raft_restore(raft);
Good catch, thanks!

Fixed:
```diff
diff --git a/src/lib/raft/raft.c b/src/lib/raft/raft.c
index 549164f1d..dd28a182c 100644
--- a/src/lib/raft/raft.c
+++ b/src/lib/raft/raft.c
@@ -333,7 +333,6 @@ raft_sm_schedule_new_election(struct raft *raft);
 static inline void
 raft_sm_election_update(struct raft *raft)
 {
-       raft_restore(raft);
        /*
         * The node might be promoted for current term, in which case
         * is_candidate would be true. But it's not enough. If is_cfg_candidate
@@ -978,6 +977,8 @@ raft_sm_election_update_cb(struct ev_loop *loop, struct ev_timer *timer,
        assert(raft_is_fully_on_disk(raft));
        raft_ev_timer_stop(loop, timer);
        bit_clear(&raft->leader_witness_map, raft->self);
+       /* If this was a manual promotion, transition back to follower. */
+       raft_restore(raft);
        raft_schedule_broadcast(raft);
        raft_sm_election_update(raft);
 }
```

2023-02-01 23:45 UTC, Gerold103 approved these changes
Thanks for the fix!

2023-02-02 08:38 UTC, grafin commented on src/box/raft.c
> +		if (box_election_mode == ELECTION_MODE_MANUAL) {
Sounds fair enough, lets leave it as is for now.

2023-02-02 08:38 UTC, grafin approved these changes
Thanks for the fixes! LGTM.

2023-02-02 09:41 UTC, merged

2023-02-02 10:05 UTC, sergepetrenko commented
Cherry-picked to 2.10: b1128c047ef22760ea5589e5fab61a41d6eb450e