core: check event loop creation in fiber_init()
tarantool/tarantool pull request #8276
Opened 2023-02-08 16:33 UTC by sergepetrenko

The main cord's event loop is initialized by fiber_init(), but for some reason successful initialization is only checked in main() after other initialization code might try to use the event loop already.

For example, some of the loop users are coio_enable(), signal_init(), tarantooL_lua_init(), and they are all run before we actually check that loop is not NULL.

NO_DOC=code health
NO_TEST=code health
NO_CHANGELOG=code health

2023-02-09 22:27 UTC, Gerold103 requested changes
Thanks for the patch!

2023-02-09 22:27 UTC, Gerold103 commented on src/lib/core/fiber.c
> +	if (!main_cord.loop)
Aren't we using explicit `== NULL`?

2023-02-10 07:35 UTC, locker commented on src/lib/core/fiber.c
> +	if (!main_cord.loop)
Missing link to the ticket.

2023-02-10 14:31 UTC, sergepetrenko commented on src/lib/core/fiber.c
> +	if (!main_cord.loop)
Yep, we are. My bad. Fixed.

2023-02-10 14:33 UTC, locker approved these changes

2023-02-12 21:27 UTC, Gerold103 approved these changes
Thanks for the fix!

2023-02-13 11:10 UTC, merged

2023-02-13 11:10 UTC, locker commented
Cherry-picked to 2.10.