static-build: fix potential NULL dereference in openssl
tarantool/tarantool pull request #8291
Opened 2023-02-10 08:24 UTC by CuriousGeorgiy

Part of tarantool/security#27

2023-02-10 10:20 UTC, locker requested changes
1. Please rebase on the latest master (needed for `static-build-ci` label).
2. Please split the ticket by project so that there's one PR/patch per ticket and assign the part about openssl to yourself so that nobody tries to fix it again in the meantime.

2023-02-10 10:20 UTC, locker commented on static-build/cmake/AddDependencyProjects.cmake
> +    patch -d <SOURCE_DIR> -p1
Nit: bad indentation.

2023-02-13 06:24 UTC, CuriousGeorgiy commented on static-build/cmake/AddDependencyProjects.cmake
> +    patch -d <SOURCE_DIR> -p1
Fixed.

2023-02-13 06:25 UTC, CuriousGeorgiy commented
@locker 

1. Rebased the branch.
2. @gumix has split the tickets.

2023-02-13 08:53 UTC, locker requested changes

2023-02-13 11:52 UTC, Gumix approved these changes

2023-02-13 12:37 UTC, locker approved these changes

2023-02-13 12:58 UTC, merged

2023-02-13 12:58 UTC, locker commented
Cherry-picked to 2.10.