Fix calling class method before it is initialized
tarantool/tarantool pull request #8422
Opened 2023-03-09 11:49 UTC by drewdzzz

There are two cases when class method is used to calculate an argument for base
class constructor when it is not built yet. Fortunately, they does not
use class fields - let's make them static to use them before class
initialization legitimately.

Closes tarantool/security#96

2023-03-09 12:36 UTC, CuriousGeorgiy approved these changes

2023-03-09 15:04 UTC, sergepetrenko requested changes
Thanks for the patch!

Nit:
Should be `Closes` instead of `Closes of` in the second commit.
Everything else looks good.

2023-03-10 07:01 UTC, sergepetrenko approved these changes
Thanks for the fix!

2023-03-10 08:08 UTC, merged

2023-03-10 08:10 UTC, sergepetrenko commented
Cherry-picked to 2.11: 0d0108810fc744b63479b3e79c51590ed2894196..65654729a5f85b478229b22f8c05ede6e2e17d9d