salad: make rope_erase erase more then a single element
tarantool/tarantool pull request #8619
Opened 2023-05-02 13:46 UTC by nshy

We are going to use rope for representation of string field on tuple update. It will help to handle multiple updates of the same string field in the single update operation.

Currently rope erase operation can only remove single element at a time which make erase complexity `S*log2(N)`. Here `S` is number or deleted elements and `N` is number of nodes in the rope. This patch changes rope API to delete given number of elements at a time. Now complexity is `K*log2(N)` when `K` is number of nodes where deleted elements resides.

Note that implementation is still suboptimal for the case when deleted elements reside in more then a single node. First the implementation searches every next node from the root of the tree. Second the balancing rotations are performed on every node deletion.

As for the first issue it can be fixed merely by traversing to the next node instead. Unfortunately the traversing code works with single level of indirection while erasion works with two levels of indirection. We can duplicate the code/use macros/copy to handle the difference but all the possibilities are rather ugly so traversal on erasion is not done. Anyway looks like sane update usage will erase from a single node every time.

Part of #8226 

NO_DOC=internal
NO_CHANGELOG=internal

2023-06-07 14:30 UTC, alyapunov requested changes

2023-06-07 16:16 UTC, alyapunov commented on src/lib/salad/rope.h
> + * @param size Size to adjust subtree size of nodes to (addiction).
Perhaps `addiction` -> `addition`?

2023-06-08 07:46 UTC, nshy commented on src/lib/salad/rope.h
> +	rope_ssize_t tree_size;
So the issue is with this patch `tree_size` can go beyond 0 inside `rope_erase_step` temporarily. But you are right, we can keep unsigned type. The temporary values will be around `SIZE_T_MAX` but it does not matter.

Dropped the change.

2023-06-08 07:47 UTC, nshy commented on src/lib/salad/rope.h
> -		avl_rebalance_after_insert((struct avl_node ***) path,
Discussed f2f and decided to keep this change because it is done to pass checkpatch.

2023-06-08 07:51 UTC, nshy commented on src/lib/salad/rope.h
> + * @param size Size to adjust subtree size of nodes to (addiction).
Fixed.

2023-06-08 07:52 UTC, nshy commented on test/unit/rope_stress.c
> +		rope_size_t del_size = 1 + rand() % (size - offset);
```diff
-               if (offset == size)
-                       offset--;
-               rope_erase(rope, offset);
-               fail_unless(size == rope_size(rope) + 1);
+               rope_size_t del_size = (rope_size_t)1 + rand() % 4;
+               del_size = MIN(del_size, size - offset);
+               rope_erase(rope, offset, del_size);
+               fail_unless(size == rope_size(rope) + del_size);
```

2023-06-08 14:03 UTC, alyapunov approved these changes

2023-06-09 15:11 UTC, merged