box: support tuple formats in IPROTO request responses
tarantool/tarantool pull request #8630
Opened 2023-05-07 15:14 UTC by CuriousGeorgiy

Closes #8147

2023-05-08 14:20 UTC, CuriousGeorgiy commented
Please note that tests using `call_16` are failing right now, because this patch doesn't work with it — I will discuss `call_16` in the context of this patch with @locker and @alyapunov on Wednesday.

2023-05-08 14:21 UTC, CuriousGeorgiy commented
@locker regarding checkpatch linter errors:

1. Ignoring errors for #8631 patch.
2. Ignoring errors for uncommented defitions of functions, since they didn't have comments prior to this patch.

2023-07-13 15:13 UTC, alyapunov requested changes

2023-07-13 16:01 UTC, CuriousGeorgiy commented on src/box/lua/init.c
>   */
Fixed. Also added a comment to `luamp_encode_extension_f`.

2023-07-13 16:01 UTC, CuriousGeorgiy commented on src/box/mp_tuple.c
> +tuple_unpack(const char **data, struct tuple_format_map *format_map,
Fixed. Also fixed `mp_decode_tuple`.

2023-07-13 16:01 UTC, CuriousGeorgiy commented on src/box/mp_tuple.c
> +	tuple_to_buf(tuple, data, bsize);
Fixed.

2023-07-13 16:01 UTC, CuriousGeorgiy commented on src/box/mp_tuple.h
> + * @param ctx MsgPack decoding context.
Fixed. Also fixed `tuple_unpack`.

2023-07-13 16:02 UTC, CuriousGeorgiy commented on src/lib/core/mp_ctx.h
> +	ctx->destroy(ctx);
Fixed.

2023-07-13 16:02 UTC, CuriousGeorgiy commented on src/lib/core/mp_ctx.h
> +	/** 'Virtual' destructor. */
Fixed.

2023-07-13 16:03 UTC, CuriousGeorgiy commented on src/box/tuple_format_map.c
> +	for (size_t i = 0; i < TUPLE_FORMAT_MAP_CACHE_SIZE; ++i) {
Fixed, thanks.

2023-07-13 16:03 UTC, CuriousGeorgiy commented on src/box/tuple_format_map.c
> +			map->cache[++map->cache_last_index] =
Fixed.

2023-07-13 16:03 UTC, CuriousGeorgiy commented on src/box/tuple_format_map.c
> +	if (map->cache_last_index == -1) {
Fixed.

2023-07-15 14:50 UTC, CuriousGeorgiy commented on src/box/lua/iproto.c
> +	struct mp_ctx *mp_ctx = xmalloc(sizeof(*mp_ctx));
Fixed.

2023-07-15 14:51 UTC, CuriousGeorgiy commented on src/box/lua/iproto.c
> +	struct mp_ctx *mp_ctx = xmalloc(sizeof(*mp_ctx));
Fixed.

2023-09-07 11:36 UTC, alyapunov requested changes

2023-09-19 12:27 UTC, CuriousGeorgiy commented on src/box/iproto.cc
>  	return;
Fixed.

2023-09-19 12:28 UTC, CuriousGeorgiy commented on src/box/iproto.cc
> +		if (box_tuple_as_ext)
Fixed.

2023-09-19 15:06 UTC, CuriousGeorgiy commented
@locker lint/checkpatch seems to be FP on this hunk:

```diff
diff --git a/src/lib/core/mp_ctx.h b/src/lib/core/mp_ctx.h
index 6230b2795..33d6aea89 100644
--- a/src/lib/core/mp_ctx.h
+++ b/src/lib/core/mp_ctx.h
@@ -36,17 +44,52 @@ struct mp_ctx {
 };

 static inline void
-mp_ctx_create(struct mp_ctx *ctx, struct mh_strnu32_t *translation)
+mp_ctx_create(struct mp_ctx *ctx, struct mh_strnu32_t *translation,
+             void (*destroy)(struct mp_ctx *),
+             void (*move)(struct mp_ctx *, struct mp_ctx *))
 {
        ctx->translation = translation;
+       ctx->destroy = destroy;
+       ctx->move = move;
+}
```

2023-09-22 13:25 UTC, ochaplashkin approved these changes
LGTM :rocket:

2023-10-12 13:51 UTC, alyapunov approved these changes

2023-10-16 14:27 UTC, Totktonada commented
OK regarding 'lua: handle MP_TUPLE extension in merge buffer source's next method' commit.

2023-10-27 20:14 UTC, merged