gdb: support msgpack extension MP_TUPLE
tarantool/tarantool pull request #8752
Opened 2023-06-08 13:34 UTC by elhimov

Closes #8632

NO_DOC=gdb extension
NO_CHANGELOG=gdb extension
NO_TEST=gdb extension

2023-06-08 14:07 UTC, CuriousGeorgiy requested changes

2023-06-13 13:50 UTC, elhimov commented on tools/tarantool-gdb.py
> +            return '!error'
It checks that actual type of msgpack item match the expected one. This extension has format MP_UINT|MP_ARRAY and this code is needed to make sure msgpack contains them.

2023-06-13 14:08 UTC, elhimov commented on tools/tarantool-gdb.py
> +        return 'tuple(fmt={}):{}'.format(format_id, payload)
No problem. I just used some arbitrary format. As I see the only thing here we should care about is make sure there will be no ambiguities with fields of other types. For now I changed it as suggested.

2023-10-31 19:38 UTC, CuriousGeorgiy approved these changes

2024-02-15 09:38 UTC, locker approved these changes

2024-02-15 09:39 UTC, merged