lua: replace `api_check()` with `assert()`
tarantool/tarantool pull request #8896
Opened 2023-07-19 12:39 UTC by Buristan

`api_check()` is LuaJIT internal assertion. To prevent inconsistency during internal assertion changing (for example during backporting) use glibc's `assert()` instead.

NO_DOC=internal
NO_TEST=internal
NO_CHANGELOG=internal

2023-07-19 13:19 UTC, fckxorg requested changes
Please update your commit message to the one below (grammar and punctuation fixed):

```
`api_check()` is the LuaJIT internal assertion. To prevent inconsistency during internal assertion changes (for example, during backporting), use glibc's `assert()` instead.
```

2023-07-19 13:24 UTC, Buristan commented
Hi, Maxim!
Thanks for the review!
Updated the commit message as you suggested.

2023-07-19 13:45 UTC, fckxorg approved these changes

2023-07-21 06:55 UTC, igormunkin approved these changes
@Buristan, thanks for the patch! LGTM, as trivial.

However, I would like to share my thoughts regarding the change. I'd rather redefine `api_check` in src/lua/utils.c instead of replacing it with plain `assert`. So later, you can just remove the define when the new assertions are backported.

All in all, I see no strong pros for my proposal and have no objections regarding your approach, so feel free to ignore.

2023-07-21 07:02 UTC, Buristan commented
Hi, Igor!
Thanks for the review!

`assert()` is used <src/lua/utils.c>-wide, instead some Lua-specific macros. So, to be consistent I prefer to use plain `assert()`.

2023-07-21 09:15 UTC, merged

2023-07-21 09:28 UTC, igormunkin commented
Also backported to 2.11 in scope of cb131f6.