box: drop debug log on tuple new/delete
tarantool/tarantool pull request #9113
Opened 2023-09-07 14:25 UTC by nshy

They are rather noisy. Also delete debug log on arena creation. These two make sense only with each other.

Part of #7327

2023-09-07 14:27 UTC, locker requested changes

2023-09-07 14:27 UTC, locker commented on src/box/vy_stmt.c
> -	say_debug("%s(%p)", __func__, tuple);
Missed one more in `vy_stmt_new`.

2023-09-07 14:34 UTC, nshy commented on src/box/vy_stmt.c
> -	say_debug("%s(%p)", __func__, tuple);
Fixed.

2023-09-07 14:36 UTC, locker approved these changes

2023-09-07 14:47 UTC, locker commented
Tests fail. Pls fix.

2023-09-07 16:05 UTC, ylobankov approved these changes

2023-09-08 07:16 UTC, locker approved these changes

2023-09-08 07:16 UTC, merged