Improvements static packages
tarantool/tarantool pull request #9134
Opened 2023-09-13 10:08 UTC by foxzi

Add man pages to packages.
Add license, readme, copyright, authors to packages.
Add dependencies of tt to tarantool package.

2023-09-19 13:38 UTC, ylobankov requested changes

2023-09-19 13:58 UTC, foxzi commented on static-build/cmake/MakePackages.cmake
> +    install(FILES ../LICENSE
I'm not sure, but It doesn't brake rules. I checked packages on my ubuntu desktop and find that it's ok. If You want, I can remove it from deb packages.

2023-09-19 13:58 UTC, foxzi commented on static-build/cmake/MakePackages.cmake
> +            DESTINATION /usr/share/license/tarantool
fixed

2023-09-19 13:58 UTC, foxzi commented on static-build/cmake/MakePackages.cmake
> +    install(FILES ../debian/copyright
done

2023-09-19 14:03 UTC, ylobankov commented on static-build/cmake/MakePackages.cmake
> +    install(FILES ../LICENSE
If it is ok, let's keep it.

2023-09-27 21:21 UTC, ylobankov approved these changes

2023-09-28 17:07 UTC, merged