replication: make yield more often when recovering from long WAL
tarantool/tarantool pull request #9412
Opened 2023-11-27 07:56 UTC by yanshtunder

As soon as replica subscribes, relay starts scanning the first requested WAL file to find the position from which to start replication. If a replica connects and needs data from the end of a really long WAL, recovery will read up to the needed position without yields, making relay disconnect by replication_disconnect_timeout. This issue was already found and fixed before: ee6de02. To fix this problem, make sure that when recovering, a yield occurs after each WAL row. In this case, the recovery time from WAL will increase by approximately 50 percent.

Closes #9094

NO_DOC=bugfix

2023-11-28 04:05 UTC, p7nov commented on changelogs/unreleased/gh-9094-recovery-from-long-WAL.md
> +  end of a long `.xlog` (gh-9094).
```suggestion
* Now Tarantool sends heartbeats during WAL scan when starting replication
  to a freshly subscribed replica. This prevents relay from timing out when
  the replica needs rows from the end of a long `.xlog` (gh-9094).
```

2023-11-28 04:05 UTC, p7nov approved these changes

2023-12-19 10:36 UTC, ochaplashkin requested changes

2023-12-19 10:36 UTC, ochaplashkin commented on test/small
> +/home/yan/Projects/Mail/Tarantool/tarantool/test/../src/lib/small/test/
It seems that this is not the path that we want to see in the end.

2023-12-28 10:17 UTC, closed without merging