iproto: fix use-after-free on using iproto API after shutdown
tarantool/tarantool pull request #9517
Opened 2023-12-20 08:23 UTC by nshy

In the commit 26acba832c4e ("iproto: don't use cord_cancel_and_join for iproto shutdown") we free iproto while TX event loop is still running. So TX fiber that try to use iproto API after that will cause UB. In particular this was reported by ASAN run of
`enterprise-luatest/flightrec_test`.

Let's make API work even after shutdown. Also there is another issue with shutdown. We stop accepting new connections during client graceful shutdown but we may start to accept them again if it requested thru iproto API. For this reason in particular we may leave some connections running on freeing iproto which is UB. Let's fix it here too.

While at it let's use `cord_cojoin` in `iproto_shutdown` so that event loop is not blocked.

Closes #9507

2023-12-20 12:53 UTC, locker requested changes

2023-12-20 13:35 UTC, locker commented on src/box/iproto.cc
> +			return;
Please add a comment why this is necessary.

2023-12-20 13:50 UTC, nshy commented on src/box/errcode.h
> +	/*278 */_(ER_SERVER_SHUTDOWN,		"Server is shutting down") \
Done.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/errcode.h b/src/box/errcode.h
index 0d062ece3..1753d3f95 100644
--- a/src/box/errcode.h
+++ b/src/box/errcode.h
@@ -330,7 +330,7 @@ struct errcode_record {
 	/*275 */_(ER_CREATE_DEFAULT_FUNC,	"Failed to create field default function '%s': %s") \
 	/*276 */_(ER_DEFAULT_FUNC_FAILED,	"Error calling field default function '%s': %s") \
 	/*277 */_(ER_INVALID_DEC,		"Invalid decimal: '%s'") \
-	/*278 */_(ER_SERVER_SHUTDOWN,		"Server is shutting down") \
+	/*278 */_(ER_SHUTDOWN,			"Server is shutting down") \
 
 /*
  * !IMPORTANT! Please follow instructions at start of the file
diff --git a/src/box/iproto.cc b/src/box/iproto.cc
index de6feecaf..16c57155f 100644
--- a/src/box/iproto.cc
+++ b/src/box/iproto.cc
@@ -3659,7 +3659,7 @@ iproto_listen(const struct uri_set *uri_set)
 	evio_service_stop(&tx_binary);
 	/* Server can be stopped meanwhile. */
 	if (iproto_threads_count == 0) {
-		diag_set(ClientError, ER_SERVER_SHUTDOWN);
+		diag_set(ClientError, ER_SHUTDOWN);
 		return -1;
 	}
 	struct errinj *inj = errinj(ERRINJ_IPROTO_CFG_LISTEN, ERRINJ_INT);
@@ -3751,7 +3751,7 @@ iproto_session_new(struct iostream *io, struct user *user)
 {
 	assert(iostream_is_initialized(io));
 	if (iproto_threads_count == 0) {
-		diag_set(ClientError, ER_SERVER_SHUTDOWN);
+		diag_set(ClientError, ER_SHUTDOWN);
 		return -1;
 	}
 	struct session *session = session_new(SESSION_TYPE_BACKGROUND);
@@ -3950,7 +3950,7 @@ iproto_override(uint32_t req_type, iproto_handler_t cb,
 		return -1;
 	}
 	if (iproto_threads_count == 0) {
-		diag_set(ClientError, ER_SERVER_SHUTDOWN);
+		diag_set(ClientError, ER_SHUTDOWN);
 		return -1;
 	}
 

```

2023-12-20 13:52 UTC, nshy commented on src/box/iproto.cc
> +static bool is_listen_disabled;
Done.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/iproto.cc b/src/box/iproto.cc
index 16c57155f..879fafe30 100644
--- a/src/box/iproto.cc
+++ b/src/box/iproto.cc
@@ -313,7 +313,7 @@ static mh_i32ptr_t *tx_req_handlers;
  * new connections at some point and should not start accepting them
  * again if it is requested through iproto API.
  */
-static bool is_listen_disabled;
+static bool iproto_is_shutting_down;

 int
 iproto_addr_count(void)
@@ -3183,7 +3183,7 @@ iproto_on_shutdown_f(void *arg)
 {
        (void)arg;
        fiber_set_name(fiber_self(), "iproto.shutdown");
-       is_listen_disabled = true;
+       iproto_is_shutting_down = true;
        iproto_send_stop_msg();
        evio_service_stop(&tx_binary);
        return 0;
@@ -3590,7 +3590,7 @@ iproto_send_start_msg(void)
        struct iproto_cfg_msg cfg_msg;
        iproto_cfg_msg_create(&cfg_msg, IPROTO_CFG_START);
        for (int i = 0; i < iproto_threads_count; i++) {
-               if (is_listen_disabled)
+               if (iproto_is_shutting_down)
                        return;
                iproto_do_cfg(&iproto_threads[i], &cfg_msg);
        }
@@ -3626,7 +3626,7 @@ iproto_send_restart_msg(void)
        struct iproto_cfg_msg cfg_msg;
        iproto_cfg_msg_create(&cfg_msg, IPROTO_CFG_RESTART);
        for (int i = 0; i < iproto_threads_count; i++) {
-               if (is_listen_disabled)
+               if (iproto_is_shutting_down)
                        return;
                iproto_do_cfg(&iproto_threads[i], &cfg_msg);
        }
```

</details>

2023-12-20 13:54 UTC, nshy commented on src/box/iproto.cc
> +			return;
Discussed f2f. We don't need this change as we are going to use latch to synchronize shutdown and `iproto_listen`.

2023-12-21 08:28 UTC, ochaplashkin approved these changes

2023-12-25 10:00 UTC, nshy commented
We merged PR https://github.com/tarantool/tarantool/pull/9524 that reverts changes on which this PR is based on. And overall we decided to change approach to iproto shutdown thus close this PR.

2023-12-25 10:00 UTC, closed without merging