Backport "wal: add stubs for wal_retention_period" to 2.11
tarantool/tarantool pull request #9688
Opened 2024-02-14 08:43 UTC by Serpentian

2024-02-14 09:17 UTC, ochaplashkin approved these changes

2024-02-15 17:08 UTC, sergepetrenko requested changes
Please make sure commit messages (cherry-picked form ...) reference commits from master branch (e04c162eb5e97e4a4d9316b4075c4a313ec97e48 and 3bf55ab97d812042aa3d73c15c5f9fbf4c562788). At the moment they don't

2024-02-16 03:47 UTC, Serpentian commented
My bad, cherry picked from my own branch. Fixed

2024-02-16 11:28 UTC, sergepetrenko approved these changes

2024-02-16 15:03 UTC, merged