box: add error details for main box operations
tarantool/tarantool pull request #9903
Opened 2024-04-02 13:01 UTC by nshy

Add error details for basic box operations like insert, replace, select etc.

**DO NOT MERGE** until `luatest.assert_error_covers` make it into Tarantool (job in progress).  

Closes #9111
Closes #7223

@TarantoolBot document
Title: Provide more error details for basic box operations Product: Tarantool
Since: 3.1

For example for this setup:

```lua
  local test = box.schema.create_space('test')
  test:create_index('primary')
  test:create_index('second', {parts = {2, 'unsigned', 1, 'unsigned'}})
```

Before we get (note that compat option `box_error_serialize_verbose` is set to 'new' to show error details in console. It does not affect whether details are added or not):

```
tarantool> test.index.second:get{1}
---
- error:
    code: 19
    base_type: ClientError
    type: ClientError
    message: Invalid key part count in an exact match (expected 2, got 1)
    trace:
    - file: ./src/box/index.cc
      line: 149
...
```

And now we get (see 'operation', 'space', 'index' and 'key' fields):

```
tarantool> test.index.second:get{1}
---
- error:
    operation: get
    code: 19
    base_type: ClientError
    message: Invalid key part count in an exact match (expected 2, got 1)
    trace:
    - file: ./src/box/index.cc
      line: 149
    type: ClientError
    index: second
    space: test
    key: [1]
...
```

2024-04-03 07:14 UTC, andreyaksenov approved these changes

2024-04-04 16:15 UTC, locker requested changes

2024-04-04 16:15 UTC, locker commented on src/box/box.cc
> +				error_set_str(e, "index", index->def->name);
We should set `space_id` and `index_id` as well.

2024-04-04 16:15 UTC, locker commented on src/box/box.cc
> +	return -1;
You can and should set the operation right here - by looking at the request type.

2024-04-04 16:15 UTC, locker commented on src/box/index.cc
> +	}
This snippet is repeated a few times. Maybe, factor it out to a helper function?

2024-04-04 16:15 UTC, locker commented on test/box-luatest/extra_assertions.lua
> +t.assert_error_covers = function(expected, fn, ...)
This helps looks trivial. Let's merge it into luatest now, before committing this patch.

2024-04-04 16:15 UTC, locker commented on test/box-luatest/extra_assertions.lua
> +    actual = actual:unpack()
You should check that the error has the proper type before unpacking it.

2024-04-04 16:15 UTC, locker commented on test/box-luatest/extra_assertions.lua
> +    t.assert_equals(type(actual), 'table')
This assertion looks redundant. We know that if `actual` is a box error, `unpack` will return a table.

2024-04-10 07:41 UTC, closed without merging